apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:4sj+6gdDw99thcf4Dbk3cQ==,iv:geeaef/It2VGZycSbbxoX76CCvP8n9vrWqUT8fVj250=,tag:S5uMjl9m0mW7SoeAtMpB/g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:kHtkzLg6RO9qQkchiVis2Fi1otJiRo6fTn4K/Z4viMLM4fzZyX6biml4JznSR/bYOUzOtGRdtIIA7p5r+Lm81fzH/bigmix6Zc+TMy81Tr+MtL/IhcQNYt8TG/dV7EQuA+/XfRuUPaCDms+RlZnsA7Oui/JCDLCw,iv:7TDDlnnBg/ogUGyvwTHeDYnaMbpwL0UEkDjkJGb+p9A=,tag:26i1QHUbI3DapY2VoIWVXg==,type:str]
    FIREBASE_ENABLED: ENC[AES256_GCM,data:4tSgUhTWTM8=,iv:s1y1oFq7ut5N/XbQhk4BBM/j9E8kz8J2ioAOSe4rEXM=,tag:QuYjR8G7MhuOIjNSm8gYXw==,type:str]
    FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:VYs4RLkeCiRqx+DslFe9CQ==,iv:XPr3nroCz+5A+z7yqENt5IIWF6JDukAl51Qyl+xXwcQ=,tag:9esgNLlHDLy9rl4WXXzQnw==,type:str]
    GOOGLE_APPLICATION_CREDENTIALS: ENC[AES256_GCM,data:xBJSCoiv1mOOfGsO4KRk8h59FgzfUt2jH1ef1FuF5AD3jUw8kNGJmw==,iv:9DeT891RQlYEyvtD0kux2pOH+iiFw2fVPcxlriegIK8=,tag:eNv67pkLI51PyyDLHSML3A==,type:str]
    GRPC_TLS: ENC[AES256_GCM,data:DCxMP5ANSdE=,iv:ipsuSovAg4f8RUGu/mpAn1qg/bvliLxr7ZXfuEbUfo8=,tag:r2QGZ7C8OSsiVoaZK+/n0Q==,type:str]
    GRPC_TLS_CERT_FILE: ENC[AES256_GCM,data:Uu0GV5b6m6hfuF9k/QVnQFAo1ekbXMoii2lIzw==,iv:P1ncaEL0eGAgnboDGZUo5hAh11R0jkX1xkgGlGg0KM0=,tag:ryia4DDtdOllgkt2QB2D+A==,type:str]
    GRPC_TLS_KEY_FILE: ENC[AES256_GCM,data:znY9x5U7ovwkGWcG5/EbPKrTJ5sLG2UE5jzP8A==,iv:IwlGjMRxBECCwOnxl5mRgkWbVBC+Q/spgD4+fbbi8dk=,tag:PQDCUU4t8Vd0u7FildbxIA==,type:str]
    GTFS_RT_CREDENTIAL: ENC[AES256_GCM,data:IEPWPJVBvbajE3rsrdy37vyzZ9N+mcOIecAKARYk3VUbf6dWLq9yTqzQt8becC7plfpf0YxerLvMtK8IevmU3bNVzSEtworI6W8p2rmRNp/fMwxg3inw+w==,iv:ltrWXOrMzodYmO2kbWBe75uR+n6Db3hvxYTpFWv4+X0=,tag:h8QrPDk5BveuUCf5+Xrfaw==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:vvKCuBSdxC4=,iv:1E/3s47UZFQThMNGddBFJ7gILrTFJk0hCTWGVY3nvQI=,tag:fkaQzElvask4G9AiLjhUww==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:nOn5T6Qy+2kCAKAHrYsVAMd+sxD7jDUpf0oAg2qKIn6R0XoekRaysGhCp2v6p8UyjZODqDJnnnxifw7b,iv:NPOVSCRGAi53WgfSBPi7UBzQT9Ea7uynxQ8Pgh0hSds=,tag:sYRnAmQwG/7f5Fbb1Mz8JA==,type:str]
    ROUTER_DB_MAX_CONNS: ENC[AES256_GCM,data:/LdFqA==,iv:L2JgPC1D7c4STtVvs8yPTq7FBP2RY4GWBVM7wax3XC8=,tag:/J3M/3tOetA+WEaOMPgifQ==,type:str]
    ROUTER_DB_MIN_CONNS: ENC[AES256_GCM,data:1PDCBg==,iv:fXEgI7WRzxeH3WwxQdWQEuVXdL4en/5821nW1Xcx3ps=,tag:vbag+rOWL/hwyca6fY+3WQ==,type:str]
    ROUTER_METRICS_TOKEN: ENC[AES256_GCM,data:vfCSy1xnhpbTCb0bY6C1pos+rIQNdokkynZ/fxJsOkEwdqfREwPgyX2T98z5APfyqLfbgNMItC+EYdIuSYBzurDw5WxoYAIhQd66hrWtdxLvmA1jpwRKkw==,iv:LU3WXWI5r7h/QQSXht0rE8FWtUR2BE3zHMaimPZoFl0=,tag:KJ6rF34QezVDjTFKK7FRRQ==,type:str]
    ROUTER_TRUSTED_PROXIES: ""
    SENTRY_DSN: ENC[AES256_GCM,data:mimArM4y7JhUeOnS4Bx9EchojvbFnSwU4PoCHUSP1mvPo+aL+y59VbVQPm76sf2KF4YNl45bHZVQkQLYt2AeDa6jnGzAzd6o1IkacOnrF9gv26ljsbEd5SJsjJvT7BPVXuqngIKexb+lxtKTMLn8HRNbZ/PEwnhHWj4nXtB5fBU=,iv:Yv0azgc7cmE1IrGFcGdj0ENm09TDXD32l3z/AAfQ2uc=,tag:5oskvePqWxKKt0+FEYxiVA==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:2AVok3RMNq05cDoy032TAg==,iv:xq7bhnmtmOZx/xkpFM67ev/7F55/5tu2vdB+U4+/C9k=,tag:8/TUJJIrCV09OUUrUJyHSA==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:QA37Mw==,iv:Yq2DTL+26/lJDVo+NdlkfNWahNwxGgcKNX9laogvt7Y=,tag:4cbaTMgKjkBNY4RDKsV+xg==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:EAl30ZdjbR1mT5sa0yi4Ff5s5eXvDiNnVAKtUOkul45JBljT,iv:eJSIwxVC6iKOxeZLvIC4VeGZ+XqrHintOXd09WEPWGY=,tag:vA+jtCb25z6n3r09sznLmg==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:RLScbvvwprJzqcf2Y7FpcufVqcX9/EEKsl7xqHVGSlRtUcDBABfHDbKZErDAqeXr,iv:HUatTO1U38J59fKdTj7QmtVfkUVZy5orvWX6IQQBr2w=,tag:HfY/ahCLE05HIviCGlB7yQ==,type:str]
kind: Secret
metadata:
    name: api-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZGtPM0VFVHNZWmZsTTNu
            OC9wQUx3OEx1L2RTVnZzWGxqNlBudlpLeVVjCktxRUYrT0tVTnNnOWRXdTZuRWQ3
            M0NsSFNYanpDcERVRndUNjFBQ1g3KzAKLS0tIHNocHNIOHNRbHdUUzh1akN2aFgy
            c0Z2ZlVDVEYwVFdqZ3JpWXQwVHVxVDAKmNFs5ECcxF9WzifHdTzdATa3un8tIWHd
            2tIi+Djm0ET9AEwPsLXT+hySDpH0WoLhbb3E6Bj2+1aKYo+FU61IjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:GoS9yD95xXgXvemd/mRPxzZXAVmte9K5EAbqXLvKcC9a3mKcWr2vzBxgqKUFtbCPPv0jf4iB3KHVyeqpBhLa2E+LEl9Iy7k2RqOFlWuNz13ChIGPkafYKBSz1lALmRoZfxnXGQv4PgB7TZWjJN1v+E41fkcTDJBTi4Wayrw86Fo=,iv:Bd4UDs7Vw5tSA+e1z9dL/baAC/zVEcCS0BFCGvZMIBw=,tag:uykxhm+B4+GQ0m1YRonkGg==,type:str]
    version: 3.13.3
