apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:AP6kRdWL/LqOEqNzev//Lg==,iv:RiR38AD4gPWTpvqJwy2PscpWpz/61wSCveDj325Pmvg=,tag:6Mgk7PcC5vFjTYZdV8Dhaw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:MwYBkqlgf77UH4yxpl95iiW/oAmXO5rSsmblYK+sSZCM9DjN3pYtPsXwWaG//0XjeQvskXrmL06yqkj4RaXeux+/bfF4JS+0fazk6cR/ZMRpULVgHAnGDiDu05ytjG4ZJvccCx51jpqLrYOUtH5AmHT/1WVxVRYG,iv:6U84exnraQagUBCEH4zVQpS5DXkAs3HuDTNu62CMAno=,tag:heIgAw2aqhONaQh2O6hQlg==,type:str]
    FIREBASE_ENABLED: ENC[AES256_GCM,data:l/MGOM8m6YE=,iv:o9Xf2WXUy6jFPdD0ngZV7KLohTwXU1IPGJo4qrzAajc=,tag:QdBcO++Dt1nbpezbxMgzog==,type:str]
    FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:8h0JSwh8BUzQlpDjqtetPw==,iv:PcP4xBxW9ItYuF7ntg/ZAMus4JpBjCVKOQ1ImvUabGc=,tag:I1yRFRynClhJiqCp7IKYxw==,type:str]
    GOOGLE_APPLICATION_CREDENTIALS: ENC[AES256_GCM,data:8+My/RVOhVhtqEj4w974wfTxrgMprB5AJs0oYjavmn62TNYyUK5D7A==,iv:b40dtVcQtaeg5+jJoFvDvR3pGIrROTkMBrgZXyzh9f0=,tag:sKhNYSG6EeJknsh6dZtZUQ==,type:str]
    GRPC_TLS: ENC[AES256_GCM,data:x4KPvRh5wIw=,iv:ZF0WrPbT5kYugNq9J9Fvimrxv3F9VuqsLL7Jnq6NFP8=,tag:QaQuZ2T+7rJW0lrZ1P+lLw==,type:str]
    GRPC_TLS_CERT_FILE: ENC[AES256_GCM,data:jMAS8rQb5ZmJZGnVbaBrpzWVFWWOnTbo3DJ6nQ==,iv:9RaTBDLk/oWd5k18Fx1hwpfmyKfbc9bVEVChvoYaess=,tag:ej5dfMma69p7L1HrhPGt2g==,type:str]
    GRPC_TLS_KEY_FILE: ENC[AES256_GCM,data:0nOXRTMIEtW8BD2LPipVBCR0X5seQxxRkIhJ/w==,iv:QZgeZoFf7SW0QXMpjXhEaksLHh8ZBsF3qMaAFnMoxN4=,tag:zCGHSLPkU9nNBaCbDli33A==,type:str]
    GTFS_RT_CREDENTIAL: ENC[AES256_GCM,data:u6VEn5PWheAVQMRTqml2IDCr0+oIFkN3Tfo/TNJ0riTLkT1R4Jw7JSB8Ms79gsdM93sS/B2uFdUg2Aveg5YlRs2yM8sPbGU9zUQSH8ondR2UWfW1ZW73hw==,iv:eBFGDkWwYrTQA9k+jof+mC1TkbI6yZzwc1Ylr1M0r9Y=,tag:dXwZnCYvCE8TlF2chQJdFQ==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:G2g6O7jXPH8=,iv:DF1AOqaKB9WchEAEhkHhlPtLw6Z8iOF/8/+iUMIegFU=,tag:CJok3n95/o5Cc1vxQAlrtQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:xtM4qep1QoZTLEC76KgiL47x41OTMH+Dw2562USXbDTNgjMyjjbNGWcwLRHirLVLofbdtZwQrN5iteJt,iv:k9qnNtRlcatAEOnRaVMrFIpkLlWDgYQx48XtAjZk0cM=,tag:hMdPxqPUMGvV6dflon4/eA==,type:str]
    ROUTER_DB_MAX_CONNS: ENC[AES256_GCM,data:667Hyg==,iv:08Jcf8JCDCfD/j3lrbHhqf6r8r5U5h3vrh268b5gf5U=,tag:PBbqioejyDaCClugmvtdhQ==,type:str]
    ROUTER_DB_MIN_CONNS: ENC[AES256_GCM,data:WzV6AA==,iv:1u4YcS/izszKn+TBjb8d/kHPPkzLFIRfkHfd013/Y5c=,tag:2b3OB9qZ4nwn0k+0m1ZI9Q==,type:str]
    ROUTER_METRICS_TOKEN: ENC[AES256_GCM,data:j71HzjoLaa2IT+z4Eat5UL9PAWziLH5QsdQRKtrvrJrBWHEFzaxxcwXr9kJskqXGb8gWLoNhFnCW9io5Wp/669wurzImKNUIySdOQ3LUgDN2eD3QAoQdqg==,iv:niIS/OoZP/lMc561FCCDOebIW6I7ty8YKMEXuFEi/yw=,tag:7AcowMG29ypdF2p/7suwlA==,type:str]
    ROUTER_TRUSTED_PROXIES: ""
    SENTRY_DSN: ENC[AES256_GCM,data:LcPSoBr10+6v5dvk8r+d4ehi67JWuFZnn4+L/khaSfgHvaAXiWyIuGnrCmaPOC9UVfpdh+cAbjziR7z6ytAeHQmXUSOfikqGrwjO1F2zj/1mKUjCaGnLQjvNxVsV4QVkVNDVbkaeMBqf1tbF8ok/h8RZyh4dWfKem4ouHBVuc2U=,iv:BcWjeDNDo8mE14bgUask8AuQvuElSe4WchS8q054Jx0=,tag:Z2P1J7+d65cbakj7umsFWg==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:Yiw5PGhxx2w584Dy29ZmUA==,iv:GC6QNj8bdVRh24xB/7OR4Y2N3jPqFCeS1/rGbCP/8n8=,tag:HvdvCJIAxsExIGTyKfNFUA==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:Eq5CEQ==,iv:6ank0uOvsDD8XHZ6QdYQsICE7Tl9/F4cIUBBfBF2YFE=,tag:qEKFwnTOFBXYtVz9iwFO3Q==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:9UzmWGI+bm6sJQxQpoxFBNfN/qtOwj+EtYH7Ob2sJRfnCCHe,iv:DNI5ffpZfPrW2WF14n0HNd3BG3zv/1VmHKlv0kiAUEE=,tag:a268yxaTAuV52OEDPusOtg==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:CrEPfQd9qronGVrcLo8tWAqoWWJ5IKQ2SQRe6xyp3AD13exZYe73veKM+hW6msp4,iv:LM7fy+AhPxgtjml+3jgWRL55MXoISvYvlvxwe87crII=,tag:XDdF3uMo/mq+sjQDBO88DA==,type:str]
kind: Secret
metadata:
    name: api-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbTcrYzBDc3VjNDlhSmdH
            ZlNsUXVVeUtBdndNSk9TUVZKOGR6QVRlblVRCnA5L1picTNlU1ZkNVBZbW5kcjUr
            akQ4TVl4N2NqOVlEL3JMN0xJOWN5ekkKLS0tIE11SGU1WkJSVDlLQ0RibzdMTW9V
            MzRBMFJyYW1HSXRmUEh0TlI3dVVtSlEKVQQZFWtjdKIS21Pg7lqy/5hwzsheSsAJ
            NYEMc18cPiyPxoU9RVrVGPfmYV9DOQp6dc92b8mR6VmcMXbSTdZPdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:qiddiRi7pf+xJ7c2K7QB3VRcXSPwYaHsqP3ZkhxhiE77f2LAVTl7hQ6sVp8pdnRpAjnSD5z6/lsOgbLJQY/SorGO8iUrGWrDrctFuH7GKyhNAhApfVF3kO6uItPMNZK6QIMNNjJS+t3cDhGCeao4Pm43JmUFrJORp+duJSujAHo=,iv:3uXNRL0e1azyemWBTBdnkbgs79d/NkKqQBJQLJURcKE=,tag:694cx02faDfd5Nv/1Z+y/w==,type:str]
    version: 3.13.3
