apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:pgUGLsUCJr/amjUnujw5wA==,iv:kK4SInMPh5uYVXBkY5EamFGc9wqEMy01z8J+KCwBsBc=,tag:Gap1yt9+wVyJYH/x7OFDlw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:VcLm/TZD9C6HLJ2N5YMBqpjfRRkCPDgvDwahYn/XLhKRcHITVVy/Te4dAu5kG+zT+MExvghALLmRDCSLEUFErCRvuP9G0rRZUVPkSgYxDUnn1NBmfzbYYUxwwiHFVAvfv3BVkYp1xhBmFerWsgRjR5P/bAW4bbMIW3RteDZjjRqfU72pjbpGR/qbv9ixXcybQhMjup/PDaRBNq22lVYFTbYS8J3cJtMwp11RskwG5+O2cZD9AFy9zA==,iv:71m/52VFv2SrI0ZqisVJLnHqNPbIpaYagAc0jBrNv+A=,tag:8agtMaZXYgJ8rTvMPlJ5WA==,type:str]
    FIREBASE_ENABLED: ENC[AES256_GCM,data:zWXiDq3lvzs=,iv:tcU0xqE4HQNxv7jabAPMCrDVajRpQBYo/EPhfOMaKKs=,tag:DTAdoO11xz4NStrjEbWjrg==,type:str]
    FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:YUf/pDnj0vIqcS0SXc1OXQ==,iv:CB8t/lyA3TPt+kVta5NCKKLmnfRtvqN6zc0nb93cfss=,tag:h3da6jUSxBACfIe3htnlGA==,type:str]
    GOOGLE_APPLICATION_CREDENTIALS: ENC[AES256_GCM,data:ncUrcoU2oTmurPfYvMG2oQS2cZTUf46dB0GvioW7zaGY3p+CjIQPjA==,iv:RNtIsCINzNWbektesFp0Z6n/49fnQWdOrr9BsIXkBb4=,tag:lcl9wNznK8/6dEo4muDNUw==,type:str]
    GRPC_TLS: ENC[AES256_GCM,data:9jRFjW+6WjA=,iv:8znLDoNsrL/AEln3z5N5XGKh2tz+hxYIGKcoIDwL5Rw=,tag:IcdGR1OmPQ1p625wp2DSdw==,type:str]
    GRPC_TLS_CERT_FILE: ENC[AES256_GCM,data:KzGohebhhyvPMA62P5T0LePaocLfsZTqYgudgQ==,iv:dRv5UJxLh2JfxnOE8sv0op1fdohqIzdWgL+ai/aWP9U=,tag:rydiVTHhcwwkpLeum/KkaQ==,type:str]
    GRPC_TLS_KEY_FILE: ENC[AES256_GCM,data:Vx/EIHgmvOdK2BcrWCZC/XbjtgIWLKhkoxFJXA==,iv:zdZen0gcYF9bAjteIYM7K6DP6pKpT2hpBNHe2aB7k5M=,tag:04fCaC4m4XfddF6XoUOy7A==,type:str]
    GTFS_RT_CREDENTIAL: ENC[AES256_GCM,data:XSuCbwbbdCepqYm+cISE2IV28AiGO/t6JbBjWxWR01K1BQITcHgyQWuAXQ97Z3hBSe2QSSyxEiW7h5fBK7RQWoEfAofa36q1PbSnVHJJWJHPoksJ3wgi5Q==,iv:ex4pM62iAzAerE825nikTltxDBX+48BNKwNXEd74xRM=,tag:5WbMakxjOx21GBAGTyaGCQ==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:4ES5ureJbt4=,iv:TqtRGotiriSmM9HmlskjwuVDwVzkT3hXf3x/5K808Wc=,tag:nb5QSxU1oleU5+4fNwUg3g==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:bqXRuf07CFg279OXd8ZPKUA4SeIqe7GewOK4kFh1BhdOeIOB9THyeweALWKHGsPDaUPWDdYYwo0LaOlJ,iv:v0sGeWp+cL5SvY04/2QyKT8qm/RM4UZkyMYZslDcQUQ=,tag:wy6kqN8bHgGiQVFNdttjXA==,type:str]
    ROUTER_DB_MAX_CONNS: ENC[AES256_GCM,data:lG/7uQ==,iv:emNQI8+oeGtreK2i1N3bTkX3UV3aOHj6/srAuq8T0pg=,tag:5MW5+kkVU1mfWU6qH0QhWw==,type:str]
    ROUTER_DB_MIN_CONNS: ENC[AES256_GCM,data:tV11WQ==,iv:98HTAH05QZyeefJxv6rLkc6YN4B8jooxyRCAeloFF18=,tag:cnbwlv6FOGdYGtD0t5Y+IA==,type:str]
    ROUTER_METRICS_TOKEN: ENC[AES256_GCM,data:gg2tl2ZmzwBd/cgnNO57H91hfHXqkeF4zWCwOBYpYaLD2VRgoGD+DtV0vxKprtHL58Ntu9zcs2wdJWZiOliubpdsEFKcjDRybcjY/CIPP2M4q9tMp3VUxw==,iv:zDmEPum+eg1B5OKgab9kPDP2k29pj40vexsm4u5rWpc=,tag:9F/0OciqftGU78bhReIJvQ==,type:str]
    ROUTER_TRUSTED_PROXIES: ""
    SENTRY_DSN: ENC[AES256_GCM,data:kwAM1aj9YDGzzTK1ifo9sYbRg93PbTQWhmZOYwPZtT1Hl/xy58iyvfPqJ9EkT40lBWf7FIGB2OUyM6mEXTLMk8ADg0SNWoyPiWvIK7vjAF3ptpFSj5d0qmG7C+VaKsMyp5M+wB4hevdvz8N4nLFoP+i6eBgBj3wLWAKeorPx8VE=,iv:m7F3vsZ+QMPKTvKaLtZ/XnSJaPSTUuSjcvx+VLurcUQ=,tag:Cqgou1nh3WUur321XNwa8w==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:1GMm/JzwbOVYXO3S5xLYEQ==,iv:E2CxhxVEvb4a/pJBYwNZ9IUa/psuaFF/HrCF4j5M6kA=,tag:ULnyqbvPdY87hnnMA3VhLQ==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:BxOQNw==,iv:L7+ooYwTlriBmE8Eq11iiXR/pgBjNlVCwnrAxklUDbM=,tag:eYpNm6tH+5YJQFhPLmAWAA==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:I/J4lZKOIRQMURRjfBelsq/3mz/JibM9gEyxEVEDTAkStTFi,iv:SZqdET7+65w/xTnq9QaRJgqBm2Xp53kJqGbsEUxKlx8=,tag:KBRx8c3cYp2Yc4zCXNkBfQ==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:EjXERzWw5uHOMjwJdFypO/Yztnqvh7leML5x/XthusoeRBqh2b1YC4hgvs0LPbI/,iv:7AVgwF4V58KkXFIRESvlv4F+YwFLlpJYnYZJZgrTGvs=,tag:c5pmy0u+n9/TbY1y7WGHog==,type:str]
kind: Secret
metadata:
    name: api-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbDhYVDF1Q0FzaGVuNEY0
            a3FHdFN2ZHR5VXdna2MxeWg4NzZ6UWE1S3hZCklqa2tBK1poY292Nk8vT0lmZHZY
            V01mbWVma3I1aUVYc1dHS0hGUUhzc3cKLS0tIFJOM0pIbWpid0tFQnpHOVQxTWdY
            UHoxVGc1di81WW0zSWh3bVc4QlJENW8K5p2VhBTRVJKP4jNNVWlTGacm43Qpstzk
            rkIDTtGWUM3R5AhjcXqWCfqzcZ5vPNcgEC5ZcKrjIRP4kiAEg7Q1qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:eEq3dVd2dvviQRrqTWAS0akUAAyjLapG/oORhSX+KwJUdbg4UhUwoe/bvVF27zDtyb9yyKNA2TyTTRXyEsH9RCDYl4yvgUXC08uUH5t412xLMDLOAmsRd+dKANdUjsiG0f9TMeEOuhq736Az1khO23opHszQnxiCAEB4Xjf3naI=,iv:LfpUv1sTZko7m1tAHDjElw43A77pzaL6YfrtDZr9J2E=,tag:5e0cmDdBwR95lNb5PPa4ng==,type:str]
    version: 3.13.3
