apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:6AQkqWpqDBZr0o2yTkHx52YNWLsdeQDMtog3oqmPHr5zsYNl9th2x08CG/bFsr0BbqsOFn2/hlQ7b+/EbbfYnfk/AZy810C+r8wXIOInfT1Bu7w1p0jhFGYhmWLfl7Ccj+8y/LRh9k3wFdBoFGHES2POKmctUdMgW4ptN47u25yeBQ+SjGnESmHqIsszbxGuOUzowTLK2fvObUIXJKR/Fkl7OSqLyQwk/HObujgbK+sjEf77jVSs4csXUl+OPjOVJ5ppEpauX9ML0CrmDcHfc5vFxnYxhj88U3YgDftNdrWRBuNwtAeL/7ssHGw=,iv:DNmSIPduWgdMSm+F4a37viVWh2JpE9vxNqF8dK/bgAs=,tag:SWIVQSC6F+s1SanDMpL+DQ==,type:str]
kind: Secret
metadata:
    name: cloudflared
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRHZLVHBvR0xRTWN4Yk1q
            aVhrV2N1SWs3Z0FuY3JwZVZBOTRNSXdaN1NNCndiRm9wZDNGZXZSblV6c1ZjR3hW
            SGV2MGRnUFFYc2phVHhBVGlraGJnQncKLS0tIGRzL29WUUorRGhmQndEdnpwZisy
            MUpwbGJMM1V3RmlMUklrRWNhanBRNk0KnTR0KMzc5OEIH83NaBaKUNDxMiVAy0+K
            GGkar8VFUiZQhKnfyEbYH1jtC5V1EqzYHh6Kx+jwRlXyooWGRcx5+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:mmPHGTl4AWn1Alkegmz/UwaPj69t0faN9YH/BbUsexgoCLjVlDiY6cEgNSpovOegLHRQSRu6BsujAY8JYd/uIuS2XK0G+Y3WXbx/n749lv6KdwsTaOuENKmPc3BxQ0unYKM2Oqc+Wk86d4nrlXRetEzp8vtmwvnQmVaFIiXn/9M=,iv:sfIxArVeYAcRMqVQnoN6N6cqZeH2GKCwWb1X+A4yqgs=,tag:rO7dUzMSMUBdZS04sQGUWQ==,type:str]
    version: 3.13.3
