apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ple7svkN4CE/5JKZrk47yeC16IFiCfz79CvhkcxCDqu+finwWBOwqtphoETsdEXovH2irDvpHnnwncRQzf7pV77w41WJjdeI2908LDPfdBbFRj4OZP5IEb3u1M20AByuCDcffThEBxeTWoKUfaevwMkvOUx9RYDcORECteu/rWNOTD8+qnvxlef5gGD/2npUg2lRZKMLvfQ0oyu98lQ1No3GgEvMdvy9tn4SotvBtyDL4BuWIGgtSJs11BtDWF/0AJ7svsrGb8WZ1HaOI/SCqUnDxxzZkg4OLDhiRh5zCZLR2TB2FN8uDwCmJ1A=,iv:ORbhnYSxO/JqEgmXfXYoctoVVqNfWC5lbCbw8lp5K7w=,tag:1r3gOJ5YgqqgvKBysPQNyw==,type:str]
kind: Secret
metadata:
    name: cloudflared
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUnNCKzg5aXhCZkhHbkc5
            MXJ2QW1qOTl3R2R3bDY1TmQvVCsvSG1ITlI0CmhXWktpZG5vNDZ5ek90aTdKNlU3
            c0JOOGM0S1Vjcm10eXQvYUpJNlo4WUUKLS0tIE05ME0wSHczcEJxOGFPeDRSZkth
            aG5lY05LNVp3anp2OU9yZE5TYUdsa1EKmb/52Kfpug78B+Qe00RUt2S0gwbDWG4K
            7l0CWFYdJrkPX9Qkue1MIQEGXB3lMHSmtPA0dJIbCg786Q8wj8TThg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:XqcRh2rnv4YnqOhgHCnQqlZN6ro5Sm99XHRQO9srNyrb20hTfEyEbgrzOyO7X3Ra00Poub9oQoGVFbDq666/TeGms4RsRCMnQN0FkWB5g9DoIDQWIwYOtdEwkOzFeFjrFFspah3fc4nvyjpHAWjqD+ObQjtdKy7JIEz76zZSCiY=,iv:Ec9SOFvx+tByH/oUiLjTD+N7SZIiIml3TsvLUasmhN8=,tag:MW49/r9ksTkJsxWvBUrYWw==,type:str]
    version: 3.13.3
