apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:9/Qf74ZVuFyn+QZjXsofSb3CReEOIOQRPlX5LhvCsEmJ9LPW7g2W86sbpTQWjPqLrMTEn1haV8ahyOiFLZtmQIbMm0BWffhRaUKv9DrZrkr6BETiNP9zxdxCvYUIGiC1knaKoyyLevPzkQcfla+P/pJLznyaX8RTnh4glLP2RZyoEtRhx9N/n9byRiWazlld5zEne9Yb5K4VVpJskh7n+StQ9iSiQMtB76ba56JlOydQf+syudphNPFLsapoT2sry55C0a+cdm6b0111PeLPc12GMZOo8D0aR31qVZZCE8l1KHwenmixjpX/vD8=,iv:aUzaUI8X5SBQwLiDzMpIiJOmXwswHkl1jcjlVRBma9o=,tag:mqduY93tscmmGJlnjlz/Ig==,type:str]
kind: Secret
metadata:
    name: cloudflared
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSmxKQlJnaldUclYvZUFW
            Q1ZwQnI2a2xIYk82TWJrNFk4TlpNcjFpT3pRCmN6dnRhMThFMDh1SnhteHdyaE9B
            ZHBRSVhlSVVEWWRidzZ4RlBMaFhpRFUKLS0tIGNUM0dmcHoxZHdzZm1pcjd3Z3JT
            L29jcGFKUHJyT3QvNHpHVEI4emVmZjQKMfpEOPxWR3fo28awTVoDC46q2o0evoRM
            HbCGpBevG+DJkZ/PE1MrI6A8DRALljK4E5N5NCaLJtjVuA2LeTgRdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:SEF0Fhvb96d47YehqJm62NndUkEk9Fd+aYcQ1IZDT8L8mcKx4oEDr61S3nElV3ly7xPww84huT+207GYmHP2JtCMaipe7gqYnO0kYuteRd261kLJcC2FNlW7KMbT2GxxDy5kFvqbWmt/TfgpxLcpsZbq+svJ+MbQire2YO5jT44=,iv:WzSS6NVrhLIHZTCanu4bN5Erng7kzFXbXAIrNCAyaDc=,tag:LTSsBGqXbjy/llyljmURAw==,type:str]
    version: 3.13.3
