apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:nO29pIsfl6OC4f1wqjZUr54UcGDz1sCU/zRHJHoGfTCsfsOLaYop7St8rvpXwRDuy+2/EMTqPdeoigD0Hgf4iPBFPNxNL5iV5uSz64eXQub/OeHLOAtU8al/J7zIFoIGp4jZ1vGIdcR2Atgnez89R1eGw2+OIUrF+/qyZsE6vuy0+y9VUE+EsIp0bmg1SNWC6LxkWOAiuwtRt02k5VzctqXAYkiWk4iblyg9rA8HbtRuAtk4IAg4/w5lMlsuCsOgAFAXqkLOzvBiSUg60Fe4VViy3TgQa1Xe8KZt9WC5ErNYkYmBjb1xJAyz8iipS03/H7cu0q4QBDM=,iv:t225SCMYfvIyDsRGOCmLIoI7TgCMma0iXqsikItrVGw=,tag:1I0xi6OXIBsV1EWEl9O4wA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: bus
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcEsxaUhUTjdCN0V3bzkz
            RDJKY1JFSDZrRG5GQTJCT2JHR3NYNjROQndvCnVsTHVib1lBNTJ1N2dtYlBKd29a
            YkJIOUlMcUJaN0NpS3FkVS9jY0VZM3cKLS0tIFhwa0lvSnlPL245UDBTOXlCc0JN
            elVKVTRRQ3RBTHMxUk9kNmI4cXpqd3cKadqDbd3xjrHnqN6EJ40jgvffZUEPj+im
            XJNWFMIpquvVBKVc/BLSJFy9R0XxlDHSfeffrSK/fmE3PhlauapSgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:0c7TcN3VSyT37HR1dziG5MLDnnlUAGw26CNYRIgC18WMDXPyK3ZaAyATmTuu9LaaArab1CRZDvrAp/EFUuZZ70KZL7/zGZx1oT9ddLdPvDOTCoYJeK3k1fToxg+VNzuKgsVR7dh1Ji2UZUXsUJ/iQQqkuQy0HzKasi96vB+d+NA=,iv:qxreDku+iowrEFnDz/GgNHIqXNDOj00WqRf9sRe2M0s=,tag:Yvt1F2a7yVOAT5csPSuuTA==,type:str]
    version: 3.13.3
