apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:9S1GeX7mDguhzdJ4FH/1dMMRp2aYvOXccsZ7PLHvwvKlwNfyxyOvBQQCfRZJOyxGr6C8kFck+QaLWx+4vzAHt6UU5isBrimBVNN0x1izj+QnaI7e8cuNiYw29deyj1418H8bRWwNbwyLp1sbGYV/xgCMyUKwQw+byZWpY6/6MBwMfg+PRlJxT/GGUujtDMJEY0drUUica54MFLK8anUueVHI5o6iNRMOh6jfACMpHAxEb0NC9fYc+dFjEEPkBRWS5LBQF8N1olE4PmXG01+9Uvp0mJyEYGhAfzta41k8GRVdhrBw0RNdpxtlKqERcfMrmeExBK5Otf8=,iv:yLrAXerEuNvl5Vp3BWA7QzjKE3FhjFcBXixVlahvUDQ=,tag:ZUxt+2TFrd11Rthuq8u9Ug==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: bus
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMnBFNDlmcnJ0aVJYQ0ta
            TVhFNW9lK3RPMjZPRmpQMGxZV0RLZE9Vcmd3Cll0Qks1L2wxa0gxNjFOK2pWWGFP
            d1NEdnJwS21VNFVTQllDV1hmUENZMTAKLS0tIGFZYUcrODg3V3Q4cm4rY2U4aTAw
            VHlzK3NBa1BQdDdteXo0aDcrM1ZqOFEKZr2kvSOuxawXN2DxEk8Ibo38U6ujnpCi
            0MoQ7w+mTpCfpnDX2KbqPoFLmMm1lm1dKDNI6w0ZsWxYuN0WtodIOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:IGZXTRtF/8qz4q2nP4noUi010NifSMBHNowSuYaiFmvEo0rj8ZsouweCf6p5OBbbt8c9RoTeti3dkhpfnZ880yv5zu4juEAdV6nWaopST/+B2TtQwTnbd8D+U0iwi2vBzYMN7Blkcyxy9Axj4juavLcCu4VtpcMvNJ3N7wTfpmg=,iv:tVyzTo+YHec8PuLCEzX9yt1FYK/d3rix6Ii3SYc8BTM=,tag:K/msRPY0/KIgP4givnHSjQ==,type:str]
    version: 3.13.3
