apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:RRBz34zzmxqiD+bAIwj+pa2kiAUzehjG+6q4EsE78oa0ck4hzqTDfk55QETITs8Ta9T6vlH1pvmO9NBpDqTZEjBnuz79WqWatKO90dQ663SWyK1PbJ7e5TS45FFXgfQ9F/eSrPF02DOSmcBuLlR9y+VLiEAi/xk0ePIli4CahGPehAh8+wYt/1nvgjruvOi78kvDimbFYG+rWpn5DN6UgP345w0jM2ah2hfcpEPYM1BG1kkbqMkkyodLE9k=,iv:3/XAlHN7bagh/kQvesoovDgciz0kuCUxmZVgdxzDBa8=,tag:CMCCod5n/RubK+qC3wwpHw==,type:str]
kind: Secret
metadata:
    name: migrate-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaWowenVWL1lXVWpMYzEy
            SHA4bElCdklKOUFjaHc0S1BSUlM5MFpjdlFVCldzMmplZ2QvaDExQitWNDZxOUNj
            TDhmQURjU2FpaFF2VHBqOXBNa053Mk0KLS0tIFNseXFFU1RSS1BNd0pGQU8yMWN3
            dWhuRDJodzFEb3lFTFJNTmZ4WEw3VjgKOJOEG7kO0nof1bjhVrz67GWuCCPDuSd1
            X58LqWjBT20TbSxAakyCd0qDrp0WbY/J7btxxqh4LuCQENbKrqmEhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:WyoKmHSrBTwm7PFdQA8rHSiy7ezung0SRBXrBzbW7aVCk1+D8v+x6hKmZf+3eLFOeOfDiFuusYDJ/bIeH7iNqq1Pzm5J0qABvuoykyMIKW3exKfhGbA2YZDzMc/ON3cXsJZPEYsJfzpYHZP9G0W2pW7atQn2YrS2ZYjOoBPHTFk=,iv:N9by4vU3ytO/B8OH8QOGOmB0MA5YGfBwd36LOZJiQtg=,tag:A1DEc6IgixwnW8LAEPiJ5A==,type:str]
    version: 3.13.3
