apiVersion: v1
data:
    GTFS_RT_CREDENTIAL: ENC[AES256_GCM,data:fhOOU1TzQKDln2vEtLFe30zpzbpl+XBB/dE4eXBSQcHIcTpx8DdMo7s60RX//etZ/J0Q223lpFwJ3eeYzmaufEPLsJvzcGoRR1g2uQb9hu+8v3wICczrpA==,iv:f7xmNftjGaRZHfReQqDre0aD7U7CTxDHaRn9WMg4rHI=,tag:lpSP3zGgw90Ra30VuTY6BA==,type:str]
kind: Secret
metadata:
    name: motis-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c0F1SzU5aXppVWRGWktu
            NW9oejJYZ1NuZmVkSHNaUHZZZ2JIeVRPNlVZCmRhZkpUQ2dhYUhGOEk5VWQ0Ym1y
            TjF0NnlyWWVQVlpXVytWN28zWEk4S00KLS0tIHhyTmZuNG1RamkxRnNNbG9ZaHFJ
            Z0dIUW5CcGZzL25CYzlyVUVEVGlPcUEK5cRGO3oJSFIxSaMPBYmhLXKHIb6sA0m2
            +miQhxXyahDDa1Ev5v8p/OhwEsd/+VDxyuqjIg9hrF+mKGDWAq6tUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:xeQbSX1fzch3bEeCHFx7yNTI7CSa9cMf5vfxT6zbRY5ietwriA2RBhGPr76sjV9CO92C64TsOUvFujpT5T/9z/3J2vz6KqPYgdMXFvHWwMLevDhYLx6bMUAQjXSuu2z47nz9jxhzx7FXMTW8d05O25x8Ww4r0e7djxxzu44InZU=,iv:xBxgxen6NK3tjNn11mXr6+6FlwjvrSMadLIz31I0rBo=,tag:sYhtFvYMSZfz+lonQ9HCRA==,type:str]
    version: 3.13.3
