apiVersion: v1
data:
    GTFS_RT_CREDENTIAL: ENC[AES256_GCM,data:ZG2ZVGI3GY9fB7XNXAIQeBiRKo2puY31XuPREtdIXSD1ErPXTVsiCuqeQergG6+uEe1hQtUjvYqC8vVXOlf/1jf/Wff1GDUcUKGrYVkGehzViUkn5MkXRA==,iv:Vb+QgGfSdvzZdAYfJUlgtGzvhvfzb7bPmItyGwd4Oxg=,tag:BCmmKw7f0bcsT0LQZNtN8w==,type:str]
kind: Secret
metadata:
    name: motis-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwalNhNFpSV2FPZ0NZU3dL
            OUN3ZkMxM2hzblM5ZXRjRzZndURiSHpodFFjCnp5a1RYeksrb3QrVlgwa29hOXNj
            Wm10RE41NDFnY3NSTG5zMW5yQlc4QUkKLS0tIGh2djh5VWM4U2M5UnIwdWptMTl4
            TGRUYk9FdlJ0SjBCL0F0SjRMeHFYQjgKxmgv9ym9eCAktCh8yqbczHDn0x4HvOmV
            gk4wA3R4SHl6qXkM3uless1sUEDNcZVNr9lMIFbBiMpvny1sUlfJ5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:19xowys9i319za6zLXQVz3l1baWp1zP1Do0X6ov/DBNyUzIWCWWZDFrhI9jcwwZ/b/uFS1cNEEolacA1T4k2s9xfe0qHd3BL2z1vdUawuYLNKjlRNcrYgKylId6iKmfNYzqVV7oCEcXOiv8Z594y/cW6JhnSv0IwCvftqVMRyyo=,iv:aXML+pF+WPI2UH+q6mGzng1Ci55YErRHgLl1w5GzRcc=,tag:V6YGhKkvc9mbeXl5h6N1Rg==,type:str]
    version: 3.13.3
