apiVersion: v1
data:
    PGBACKREST_REPO1_CIPHER_PASS: ENC[AES256_GCM,data:P+0Lu1hnj230J2KjDPXRiwAIEMpAnc4ent/HgHUzETbxpraxuHuBtHbWpz/8JEk0f5khsl9aXM4JoiIU,iv:sNs6mc9V8E4RhqMmC2B5gdOjVjRYlP3uA1/9xD+aRfI=,tag:NJb/q8wW+V8u/3dbvBLnVw==,type:str]
    PGBACKREST_REPO1_SFTP_HOST: ENC[AES256_GCM,data:kZFgDew+VGicARO6aP4ZjLi2Dx4=,iv:Pcj+xgVHQj+ncihUvG0hV4ey19HJ59qsKaxm6enThro=,tag:GxQtT30VyJylqnXv1Syuow==,type:str]
    PGBACKREST_REPO1_SFTP_HOST_FINGERPRINT: ENC[AES256_GCM,data:OSG5QASGn2I7YzRQX/oy+SU7ePpcXzaE8lmFwu1SttbzV2l4COaYOB5SJC4FdtE/w2JRC5e4tVk=,iv:KdyDkhMor1I5U3Bor831bJ6yOU09gXzA+DMxctTVCqY=,tag:Icn2vBAKIW5+pCe1/T5XHA==,type:str]
    PGBACKREST_REPO1_SFTP_HOST_USER: ENC[AES256_GCM,data:Qxh8L1pcVrJ7iFVfgNoMMe141vA=,iv:pZtH0HphmhmGR2tNSEPQMjXBtMku+nhtfzYlHPTtVTE=,tag:55B0Nvdd2aU24+YEFJH1/w==,type:str]
kind: Secret
metadata:
    name: pgbackrest-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWjVtWkpDZEs1RjhLVXE3
            MjlpcXppenBkZlduRkR6N2ZUY3ZMU21KMVZRCnlBSTJ5YThIdFVHMWtURjEyS3d3
            Kzh6T2hPd3o2ZkpTaXhxWEdqQW10eEkKLS0tIGVRdVRxOHdtalBjZkZMMEdudTFr
            VndzUmQyUC91WHVZdnJyS2dhNGZsbFEKqS6/2gDI6PcW3M8T9WGDLm9712gmC0NQ
            JOXdBf9bDjARFXgieM8n4hMHIpODewg/Gp7aZW3A1Of32yzp5ObtVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:b1skimOer04Hcn8c2hqAgeakdv1jJJ7P3aWgJmjSVTTH/OeDN7L+Oignlf720PdGYXXqslQS11z7FV8CquTbnT9sXdx/j4/yYOQBZyqxEwHhRDGsJMKrLYfkQBApqrCtCXsqscsArOMJnTovaidvgahjE14l+7YN3xxTm8D/vgw=,iv:vD/Rv0Ib6+Ho11MqQit8DPOK+/kRwOCcy49M3MUT+qI=,tag:NJiuLaGpGHTOtNUMeRM/CQ==,type:str]
    version: 3.13.3
