apiVersion: v1
data:
    PGBACKREST_REPO1_CIPHER_PASS: ENC[AES256_GCM,data:Ax9VCJZX5ymo7ihU567n5auyKE+u6ZxqAQeFNhprKCpweEpQzMCMxpnLpbJuDEW+xSk3xKWCKIBl+X+x,iv:njOQUq8AjquQF6+uEIdNfGFkjLghYsBeWnp8OntjH5s=,tag:cle8kGB8wybn6Azn9UOqnA==,type:str]
    PGBACKREST_REPO1_SFTP_HOST: ENC[AES256_GCM,data:c8D52oUUqkLXBAQw2WNoPZFZeXw=,iv:v8NjOUaBr7SCjy44NDOgvUuAQHPg3OJur3rfiOEy0Z4=,tag:C65zeD8rBpz2xquSPyLMRA==,type:str]
    PGBACKREST_REPO1_SFTP_HOST_FINGERPRINT: ENC[AES256_GCM,data:Wxuaxt5iS+O3Hd3ssvxteJN3REBvl0N0ILRr6I1J3OfYTBcZvcrlGQWcI0VK64giMKca89DGFfc=,iv:Tm8PYGZtNlUBN+UrxxiQ/QD2tW08DTI0Em5hCOvymVg=,tag:eSEUMDagu/AfEgkxJqwEZQ==,type:str]
    PGBACKREST_REPO1_SFTP_HOST_USER: ENC[AES256_GCM,data:pCjOtDaydC2r4oC9muZtKogCPxQ=,iv:Coit55bpvhI432J/h99IbIn/tI0Pq4BcN/jiQg42Yo4=,tag:mv4lUHwJ+XuuyH872CiZxQ==,type:str]
kind: Secret
metadata:
    name: pgbackrest-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSek5hdnlYWGs0c20zS1NV
            SmxtbEd1aWcxeFZMS2NZU2hHZllsRHJqTlIwCnpFcjNYMGJucW9UODMzR3hYNXU1
            UlNqY2gvSVhKbThpVXZoY1lpU3M5NDAKLS0tIFRYREFQOGI2UGpZSnh3VVBxQ1h5
            NmtOdVIvVTdDbUlzR1ZYaDVabmwxR2cKcpqlZH6pifGjx2bLOjl7yJnD4vryD8js
            fL9VDocll9C4hBxNjk2KwV6eg0Gssj5mI6NV459YNeZ3SJfsE/hGPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:zAl57sLjYrANLZVBqmHSElxndn5mNDgNp0rRwb27aNommt4hL5Bk4UqeBDy3zC6+ekPHzs5GpMidzDiJJQMkOm+gqiPF61k1prgJYaBKlS+tomdZIz9nBwqRE2/xZlf69mm2Qerbqy5c+NzoqxOn4PVtdTVI1U8DH9jhGl5z6+w=,iv:/qbTLoUFrvc+a0lijjlYLCtTwG5ojcO6in/D0fU8T0A=,tag:TVeOwMIan1ypw5QTm0BfBQ==,type:str]
    version: 3.13.3
