apiVersion: v1
data:
    id_ed25519: ENC[AES256_GCM,data:3K4xtHJlU2HNR4w8nqyVH33xqGW0zzSOThqON6kQ8k1DQZHpKs4MwESX8knzkPL13/eMvHRMUrXfNsKdB3QMQn4pj04vUTB4cBe286//nlU0djarc8CUdV/5P+T+x91WkjtSnm+VOoNlfFfrJ75qsQ+OmZXCy/q6BrMdmTHRFJndU+X49FsEFPgYjfvSNhpl+fR3ZS9yMvjmDI5PhvjVAgj0Sxrv7AzuGmadV0e5k0Rs+wY2meB60jyfW9bs3ojM366MfgME9ykcKU6I1uokggPJXtzhnnirTle90kMxmpkwkkHC915MzQn1JrAQvJiAwi0+TwDPDlqWzo/7QcCluORU8c4pNsd326P/sUGBdEjM84OpOEdX3BI/Mmzq1P8EpW3B9oCEqZ/JGu2xnxC/8r3RxW+ZrijXrfrImEimzenUMZhXkpLe0X1y2e3g5Bq1qmPaVvwiebp8nkt5HWoHr/+EqobuT84xxGgiI/yl71mVX44dHit573PQ63bWPp95wBFl3IxTfYJiRtIeavE75QKnyZRAVw6VtQcNC9/R08Ua+nkcmgdWcZDQIalQNov/4AuJWIrJdVkzJVB0zqMXnzlHWI8hAVCVXmMcthtEldV6L6vp41SoTrRZfmAZVPzNs/77EkaXYHUqdxm6jm+eskwoiEhNDhQKnLh4DV0I1y2w0ISXgrj6eR4C5PGOsPH2vwkkHuJuBnhnpCK8iKX9NQHuIeA=,iv:pp9yjaWykxMszg9JiJp6Lw6lE2axt3Z+skZ8ga80YoI=,tag:0pTiN1u+sfkKG3BLb5hrOA==,type:str]
kind: Secret
metadata:
    name: pgbackrest-sftp-key
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMGd3NFlPK1g2RXl4c0ZF
            ZFVkWjIwSTlaN242eCtaYmV1TWo1YmlhdlI4Cmh0WnNWdkVGUEUvOXpIcUtOajNV
            NjJJMXdneGpxS0RpTGJqcVZkZmQ0OUUKLS0tIC9nQlQxMERqMHczdFdySlUzT25D
            Y0MwVjcraHdXOGo0TGZnRFh3NlRNT3MKKkNX3EYIxBmWedaEAeaFn8D21/77gep0
            KSv4CaFQITj0+mKBAXtBrDUQkqLZwqbcDkxE5FPJBouncQj/BK1GUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:SXpHEdnM0GqT9WYIxfnsOJJRaSdZ7IiTIburXr1uMWheLYVnerUlrin9IOUC1fyjLZ+UovKwUjyj1huqD1mKC52Dommgvn1a+LNuIWoWb+bA37ZLeiooU1IJHFsAXWsqFJUyh2l2fNrn2FfpHsWFzfryttFHXEvRokJEmG6SFBo=,iv:dTbDtnwAMhsddVVd/Rc/PyLf3tSj+AyJE1558YJ4QAs=,tag:dbgXzv4I1zNZQT0x8RQpaQ==,type:str]
    version: 3.13.3
