apiVersion: v1
data:
    id_ed25519: ENC[AES256_GCM,data:+UWPcRUtA5U6/GGT73r7ZQXbENwMZQFm6ZvcQ4Ab88flS9zIf51UEn697dF0pzF75WiSQ9LwKz5SB6Gp0W2AGPT8G45gtud2WoA4cY4+ldaSni28EPeMB1//7u+a75Bgq1dAshAihoVQa4m0zN4F6IQJgeybMdzQC/EQaaA5aWW61SPEZLETNwDAAlm/4HcnXyA3Az7zlPLa5CBG7YZ2qP/ePR2sZB4cTbdPhq+v2fqbYH67rjKSuY0kbO1Sn+iNODvXXwGgZ1ftY7W8dfWRaZIcpr1i7lhIx22sBSgPcM1RieskkUut55Toltg2XArB1s3sLSFNieWr4AfrY4W4PAd7Vfb1+ukwp3IlQ9V3FwhZUH2eusXfI95XuOLfQOJVS8Qmbdi3Gtvzzw+xavo67bAdGBWbnswORoQBsuHAZXzWuP4iAs3Sqmu0n4uXGbb47Wd7HbwqcCoHEcmdXywLn1bisltMy5AAXsxvqD1tNRX1DBczGXgKsdyk5Uy6cwczZhwYte2cz5DROObOfk7SBHWaXCmN5y2nYzsjWy7C//bnQ4GE9FHiyrPW+X/uL9keVrVLt3XdaWRgluMkbjlz17Ykz5et8U7uzHGBQx/hnObj2MxtNqhPO9t6s8tN3g+xPaeDcNo6yTFEkvIJM21te2X7kKgNaXj/igkYL8REbq8kWKB8EKYkNIJ10DoSTlWH150GXJg9RL8VxWj4P4DSWnqbpTE=,iv:WkXLVy9SuK9G91segdlqi7uUPsemNoWPAV0I5uueFZg=,tag:KhlR+2Kk1BLp/sMWzoBjAQ==,type:str]
kind: Secret
metadata:
    name: pgbackrest-sftp-key
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOHhGL0ZvZWpVdDRnV1RS
            Wkl6RWZMQVRYdDZHRUNIayt0ZlQwNFhnckNBClA0U2lSbEJCN0NZdFdKY1RjTnJo
            bXdlOWdDNnlSbEt0WWpMRWVsWGJPS00KLS0tIHZEYkp1Yk5mNVR0NG5ta0U3eXRT
            d0VVQkhVVTZVU29QalpNcEFTa0Z3b1kK40Mleoladv3GbgFJgoYEYVfYKBaHQmc0
            UGmCqbrNI4oLQTygP1dMVyuSl4phPEuwFg9RhQtAksLvHWwIAJe/EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:0h+BTHSnH/3CIq4PGCp0JP5bScBS2R6XSB6K+wwj0tQRSMhz2tBU0SF0VeXFTXTHmKLB9DQ5fdsIz1/R21GHYzXj+3BrpqWVFRJoyGrSakQiQC6AbUMu1tz5v7i4qEfcin2E9pT9OrSH3ITuo3dTnRlD86j9Jb+petbWyA+HazI=,iv:lAMZouTuInlXpx0bgpJv7pzCXGB+pV+GpAI9sotKPyg=,tag:XHuXDhXcQnxH9X8ifuyCLA==,type:str]
    version: 3.13.3
