apiVersion: v1
data:
    PGBACKREST_REPO1_CIPHER_PASS: ENC[AES256_GCM,data:hTmzI4nF0FWZC+7brB4M//0KwTwJXuySE0A31hNzYz7CW/0J9Xgp3lRkU9RQabpS3HU244u3AAHcbYSZ,iv:1iKyJw9KLK5PVn48sjJ0TNcHeS/x5+DUt49yNskImxM=,tag:2llcA7FQwJ9nsFjpAVTSaQ==,type:str]
    PGBACKREST_REPO1_SFTP_HOST: ENC[AES256_GCM,data:YX/MQW4jg2IBtWpqEUOTIhIzoGM=,iv:HSfK3yGyney2FGn2oTAlo9lI9oP4F6STX45LhqkS7u0=,tag:VOTnrvxReWWM5/oAQRPgBw==,type:str]
    PGBACKREST_REPO1_SFTP_HOST_FINGERPRINT: ENC[AES256_GCM,data:Cvm47E9QUHAO83ftHdIL2C/rvcZd0AogonkM/GXQUtt0A4xF3t0d0YfGGNQg6zQXg5BpGtnb9ZI=,iv:KO89kygB8SkNtdwJePGZEscPSK0sfvUP2GmxRvKrks4=,tag:4NSd7Nd1wiAdFciyasvLWw==,type:str]
    PGBACKREST_REPO1_SFTP_HOST_USER: ENC[AES256_GCM,data:DfB5HrSG7wQ5gmVasKCTk0FdSUo=,iv:3XleoHAo2LPccOEzd2eimzKZOBBGfPjszYdBq5XOFt0=,tag:oqBtfNTf7mxa8szdbu54/w==,type:str]
kind: Secret
metadata:
    name: pgbackrest-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESU5pNTEyYjZQbTRPNDg1
            U3drRjNPU21uSGpjUmFDcDJ1TTk5RTcvVkZNCjdJS1kwY0lBN29wWWF2R1E1Rlhp
            eVREWXhKL0hmTDJVWEp1U0o1enIxTzQKLS0tIGpadTZXQVJ2elZLY3B1dE5uSGZx
            MkNiRVVudk80VkJTcnRSWGZvT1ZTUW8KI3K7yp/+Stq/XGvOFXHLKQUsWeRV+Ck3
            Z36CFpN+Gr7tkzTE0Ql2b6M6/lLybWCVF0aLZhr3BJb19mNuNdyjlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:Ftx7f7E1ZdQpBuQTdMefbI5QgVQc+dWxRaadFFhECKYdn71Sr9VoRyznYxtdKlfU/rRnmH8Lwpdv7NnIFaSCp4QdGciuwmrTyuEn6DP8jdQEZIi8HtApArW8AzVs7ek0gEYT4fBVVtCji08nVEQ2orLb07QfxBolkqgbctprkXU=,iv:HzcqBM7kLOLftNU2Pm//QE6L3w3H9pL2YWNWJajhdYg=,tag:JbZPybsTqDnNp+nWoIzyJQ==,type:str]
    version: 3.13.3
