apiVersion: v1
data:
    id_ed25519: ENC[AES256_GCM,data:M9+QDQ0QLQOiet0CBaCAHnQREioe6sXipIQF0QwxT5dOqQg+ITuUX0s9tcs73fe6wDghlQ1arYUCyAzNSnaWQAdNMsCOT31Jewba1xPsUBIOnXwNKQVuuv08/1rnFAYxGgGfYBwNqOuDnXtad+4QgNByVu+QPUzprAt6ZG8bNopvaimydnewnTwXWWX4CfOo5Lz+/BGJjYFf0neYxJVs0Tqs8VWsfVwLxILl51aQO6N809m06mV3qM1NcZusmuisIYRL0Rgr0AAIpz2CVWxK4TsgiIW6j+CsnnrsmJ+HeO9SkMoiXwNNttDkKdeTc0ZfRy7o5uz3EyTOo9aVSSHCMjjsP7X7fkehgYUJ0ee6wzke58KkmaGIQf0gJyLPTZ4xbX0UIctrcHWi13wGuJSuUzLlKF8//zYn1J1eddH3wpnSFw46Lirhz1+XQtaDBXDaLkEB2K+XaphH/EqOFANkCK1IKWNcjlAIY5SHS/BGYFhEctIhXzT8rE973I63AxhkOmo2lGhzCuQx0nMGjOQUa/ADf30V9Em3EnLQ3j0mzrkgmQoLQwKEVaAcHPdqyKDX2YZ7qDw0LUnvhcga8cvsmt2KHbo3Pfz3FcHuSPAgYOTEg3QtxJ8XMSWjG1+08N4cbWQgdL4CnSTt0IDJ8aNjZzjGEgHvSHBJmJrLlwCkOZDVWyFZ+tdiQj0LmeNI8YM+iJaB5BHnhYDcgH/9n1xcejhE2/k=,iv:bfPaGYJMrSaX6NMoUSloXOXoucxPEk5yQprk5wc7mts=,tag:8mwQVaj81YmLY/We1bQiUA==,type:str]
kind: Secret
metadata:
    name: pgbackrest-sftp-key
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNnFaeHE2Wnh3ME5IMHpt
            TDlJU3VWN0N6dmpHc2ppbzJmYlNYV0poNzJvCnBrenFuelFyaUNaRDQxMTk2eXNK
            N2FKK0M0N1pMVnQ1cElUY3J0ckgxbDQKLS0tIG9OMVZHTEVHWnJjcTZpTjFaVkFU
            RXdoUHZQZ1BFOUx5eTMzS0RLQnlWL3cKRmJhmr2cLMyL4XSQwlFRlwnfPIIdZ9L9
            xj48LK1MW9T68kAVQ5DuoLLNiqM4ddQpPpw6gx+RKXzGf7AA7FccVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:GostV7D66m4JyPknMnpJWHSECN5I6Ms1ldjC9Mz1uKLVDCbn6xVqh+nkjgTEY0PmGDnNovvB+AkonoOvRQdlrNffL2ziopSC+pSTmYgZNxhnpoiupSY9qUSdTIlT7Tp0D+rDcDFBg8pV9lefOMBf3bDx717ZX3+bjW1phpu/v7M=,iv:PYgnb4eH+4tz1geqQGOe/WV7xOKiCP8jW3/Ph5MxPx0=,tag:MzIZKYaUnU4oILqpYG1JGg==,type:str]
    version: 3.13.3
