apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:rwTonK7vPa9iqoufJ1GvBywvrxhiahJxT+H60pnD1wHLv5nFDVSWNlGkT5VcTtbwPKghv6tDT986PNaZDbsJzsx21BQfru0ZrRYRaIdFhPtRmro9tIv/tVLGLd1hqzWGD8chnllNuYd5ud9BSPYk2jH3sHcIaNiK,iv:iJURbaAC6tBk5lwDQudXq1M3wHiUbCK7GUnmN/occ/M=,tag:zP1xlfTDv6bKCO+BJTz9Ww==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:fBUOaQ4+aqk=,iv:IZGIxzXjJFZbz0dM5I4AqOXnsAVkeDvLlraPxqPDz2M=,tag:tX7Ou6r5fYHmIedZW8PP6A==,type:str]
    RAW_DATABASE_URL: ""
    REDIS_PASSWORD: ENC[AES256_GCM,data:wzkCCcwPcf8mzyVauFyzcjaZIUi5FEjyoeh0TjbzsGWVFmPfPTUhF4Ue0WKxeyzO7mtEr+vegji6qIvK,iv:0Qt3bUVIPYRUf+P3nMORsqDxIiKHb9NUyMPmRswk96o=,tag:AJjCXvdlx50ShwiDa4/00w==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:Enk2rtK2Wp33J2w+Gdt8kRO3JSyEt3CkPymPqb6lIN8GyJqSR1/aG0bpTi5owaFzPeCJ1fZnjfwo6ZqbPFvSUDNDPUPVuHt2lAO0wII2qUn1nP1dWZSmLyEs/HsAP3C4Fg+aZ/4N3PMiwLjXTK8qdA5NmeV72dTGyDi9hTQPQAc=,iv:eVCHWJVEXSYK+aTO3gbjFgYFhurZt19I2uLMGLo4rho=,tag:6Lbi9IK4KQIxNb5FsFVpCA==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:kquMuW3YSziOXo059+Mfkg==,iv:2doslKfXNY2x+Xh3q5t2d695IfQNsDKgMBI8AaQdTPk=,tag:RKBrMXPbCyuWbzUBeKQ9/A==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:xBKCiA==,iv:1iUAAeilDZy1+deXZaWqeRAcFsqMBxwofFM5vjNggj4=,tag:dMUc8Fh8r9zI7rALMPfuCg==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:kPF52oM/RQlEr8cEIiW7fxHaklDqEDsxROCY69EJnvIQIT3A,iv:sSLeF0vYgkqcWPalsLsCttwK4wijj3FeQfnIcQgQv0M=,tag:v9KqMTDW3zJvojKiahjevw==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:Wq9xZjfcBE6/wOeuVtv0VubfbM/jMzOCoRbKs3N2P43Temg5fa+pxeYMbOvsbjYE,iv:DDeFpSKytCITHf8hxqg6E1lQ/sdmiZc9+5pAq+ILju0=,tag:rtcWh7Rcz+oQ9++TkoO3tA==,type:str]
kind: Secret
metadata:
    name: pipeline-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eFlzR2RBOW1pQ2RzalpP
            M0hrVUdqaExJVDc0WEU1UEpteFBZc2ZRWlhBCmt6bGhtL2JrOVNqbXBKOWpYaWdU
            Ni9TVzk0bGpJSzc1Wk9KSzhCZ3ExV3MKLS0tIDNMYS9oVDd5MldsaUQyTXJHaEFD
            OFJXR3VGdDlGRzNFYTNYbkRtVkdPL00KtI9rDJFNOgUBxYQl5VBigBxQuhnFjWr3
            IO8ydMTgoaqt73Vcb0MDmOwG1YG9d2Sf8Qdk7wthE0NRJxSfOdZBJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:8WR4bWrl6fJ2CpNklNnPMlha9tkqhBo66J7vQgnuwqRv4PQu2kO+XSM0F7jFXH6t6gEWi/MS0AVMenKTry1z3tia54pIzgpj4cYom8wxXbP+ARr81MIKjXePkOpBRkor4AdUB+08qvFVYQBVdiWglICSdb1nbdmBS3IAbHFSyGQ=,iv:1cwAtEyqZLqYwzos+QbfRr0uTYiqsIIoSVhydKX8lb4=,tag:QhuSPUqF3N3uvx6VTjjMCQ==,type:str]
    version: 3.13.3
