apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:/UsdT5fpF7eufsymrvggSihPQcAD/qFZwMZzQtrM/UB2FWTkUHhAcQ1JC3tKGv7Fl/k/Iu5vepPEUdUPNko1FzzlOXgI/6yfJIhIl7QPNyVPdPZgTYiFGP+0TZzbbPed7kbgFR4MkdMe9//hlDBsUrNtFy0JuTVczqQfzG5j7gz9gZbG1A+C5Sgn6FcmrF3UNnmXhUOPCqIkxvNWTYUaKcSF8O+XDzaqf3f0FBELV3dfd9q6wB0iwBya6vQ=,iv:ndfuxIZ4M7/QGzWldYlE3GAL+IVtGqAEHthRDiC/AXA=,tag:H1dRmeLIOQ8ibdksNkQNzw==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:59rJAVTcx5I=,iv:fSp8gvdvtT5Kzr09OeGrQrwxLh22BCmLBupxbFMjrzw=,tag:aOPqDoCXxF/X29AHxukpWw==,type:str]
    RAW_DATABASE_URL: ""
    REDIS_PASSWORD: ENC[AES256_GCM,data:1sB9SFJ1TAYxeBgUP7Y83aSDgPFVKMFJHA7YFMZA//mPZNWbMcDbUls2APB2WCe3vyUxNjv/kOXja0R+,iv:iCwXOnuBUoS7L5vDzC3jWHGMzFRP8s3jV0bsekOVcV4=,tag:XMcqD+yOrf2+N4cYPI9E0w==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:+QhFA+tG69ihx4+nZBtUn0KYZHnGHB3qVRRsr/yaxtUM52tt797AUYtGd2kbtFbiqaGTejrLcTHBbAyBgfdeP9smaxRDOUkqON05enxLHUwrkyIjKD/ZG5UDuz2RZdFqENNMbfKJqAYMAaZC7fp6DIKM6z2H6On38knsHBYUT90=,iv:r4IXnyXffyg+BjGfBmWfKaaVPrPFFItaht7IqSZEWq0=,tag:vHSLsqY50IP0CwBYmlvPGg==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:lX0FzDcEy7hH7/oMlT+DOQ==,iv:yTHdbXrMfL3HI0Ibp3IozgsYKU+RBR6eMHPhiQhzX+E=,tag:mPeqV33cSXSPI4e56xDHoA==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:ZLgrkA==,iv:gNmhF2A/wztIaMQbbaCmUdIc+nXutTK8wjrcu+qXIpw=,tag:kSbJ+nO0IKNGRq+HXUYaLQ==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:A4yvXKq52RkThieXOAXjtWisv+BFXS8wXfZqoDenhjMuYnm+,iv:M+odbNVRUVl3wQV9Ubr6x4Bp2D4nPkp9ldG+w+u/aho=,tag:U0MWaG9LwN0plxek07Oyrg==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:1pDzXOYkdfQSdbMiM3bAwJEZfZloA2hbxOEFp8vG0Nl8qVo5pOXPAFxjILVUQ+Il,iv:Mlnw3OfPLkeN5gKeTU9w8pXQjygModzMdDZkie9DWqs=,tag:Q7evIJ6A+UoqnOGhHLx7gg==,type:str]
kind: Secret
metadata:
    name: pipeline-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN2hnaE9qcm9FeXlWNnIz
            U1hWMldHQng1US95V3pFSUZKY01mWVoreGhRCkJ5VUpabWtKcWI0ajBBdWJtUWRn
            blZwRm1iRUtyNCtkeWdaMTZwbDJUVWsKLS0tIGpQUUVISkU3TWEvTWVtODU5UEt5
            dHBWU2NSaWhVNCs2VGZJeFVpWHhVSDQKfUqqkJAnyUie96vkQZ709YpWlNxvsSsk
            7jV6dHdSRUWts3dfTT7kdAI4PAoRFxH3dWVlYOwK8sKiRVA1nZXvqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:56Z"
    mac: ENC[AES256_GCM,data:8a1buYDk8dxZUHD6sqRQ/6L9eb52wWY5rS5XOd8mn398wV3S3lzlVFObfQjWNWrvLhEvhTCQh9gw+y3kIXb3NoabVtYUtaE4Plw8A/qAXeQB3TblnECrUCf+1ayTADCVuh8tqWLJiPi5SdN2+TcK9OWZRzMhArap+JbkFnChb7s=,iv:JpnDS+ysOWwEXQxI4v3m/yHF9f19UuvPi4m/M3yrBUo=,tag:+MSz44XhiaPbEEYO43wX9A==,type:str]
    version: 3.13.3
