apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:iU1VqNEHCgeJR5wosCjO8qqLxu8xomcRehnAdxXxENLiB3mOTJ+PPyeAzEh0Qrp2oEFSnKJsgHexLBUMG/sr+q3X+zxhrWaREqeUaVCD8noXAVsLwo5dD3v5znCH/P4tY1d26im5Qjp2wt8CXhD8mVymZrysMqFg,iv:SUVoNU9dkmOXZi6s6lhgcr+4EHey+sPaVNa0y5Qdiug=,tag:gbFarNCcvkH/BcTzYs6qyQ==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:CB77H6Am9dU=,iv:lZLHnp4ehB0Mn+B8aqXXGme72Sq0g757e/yrgTVcHEI=,tag:lOc+04kMOXG0klkwSRSfFQ==,type:str]
    RAW_DATABASE_URL: ""
    REDIS_PASSWORD: ENC[AES256_GCM,data:tL7Pipn2veRDh/3x8ge/PkkhxjuPLiepo4A4hdOO5T+QAKPygprfsRI39JDTDkHGbenckNTlsYyu+bca,iv:C80SlnUWIPGLBcfnxmnYaS+gvOMoRCaveDzw1eiTxpQ=,tag:JCwAK6MyXCDcpo2tFQDkqQ==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:TDeFwt2/Z/2dkvx1EypLwPt+dIToooj8zJ4w+1vE6NenhaW9AIpKnX29bFZzSLh0aAMXeX4LHSh1kYBaQtUrBLbv0PNjNIyjOUcGgfJAqoj2CDDcr0lbq40KamkKLb/6U9UDK7xSEztOc2K1g9F25gpqSwzhcWSMMHKsxbE5qbU=,iv:7rKb+4IeQ9Y0ZTffW02F97OvssBZaHsyHWdO89RAr3M=,tag:1mOcKhwKDG9PmGMkFBpP1Q==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:sTF04pTUhqMlX76wEcON6A==,iv:/xcwGhE/z3dxKsqpvhjggJJivTTi/NIemPyXS5axmis=,tag:WYvuzNiJXnhHsVbTeeH7OQ==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:8b1UZw==,iv:E+m9C87GOUoZXvZe2m0K59poD3n3LH4ofYjnmKvXQcU=,tag:5n3L3HbsqgZWiV5+5arXyQ==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:wUu81lyUCftUW/hWlrENvPapgknr0Q4ZdpBxjlygnkzz38Jr,iv:1qH5F6H53OQgcfzw07UAG8+k4e/qGgjOaFM3VJsYQB4=,tag:cc8D8EgjKHPutLNF9U5MWw==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:sXqZnMc4nV9ANs7G/BjpTDVHQ9yIVB0msYYeExH7o3GExgQfBQfdVUjlL7qSa1ci,iv:1GmmFossZb8X72Mqcc7W9Q6fsO+6+NNdCUvxOD6S5AI=,tag:UC3FEZFfZEenc/4H1+09/A==,type:str]
kind: Secret
metadata:
    name: pipeline-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WFdyN1ZwZHdOOUdMbEs0
            a1hSejdHK1A2SHZTbGpYNklJUUxyK3BaR2xRCktiZi84angvQzdvZkFXc2ExMFlG
            MzdRY01Ua0crUTRrbkI4VlAwSkQ2OUUKLS0tIGQ5cU1aZUU1b1lrbm0wbmhWR3p6
            d1ljc3BHV0FjWmhzTzRvQnhuM0tHTVUKI17e+NDDpBB//64dsPxwMd8DyxENBOuj
            UZNQVkJhrFMF7MdgEtpVQ28Bz582qcYpGWdbZdb2TppXeoAjlbVeLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:Vh0NS9Sr3348J8QLWR4l7btmEdlP0uuFY8p8hMiEiocfSzyb5m9OnQaQ7pFPXyJmS2URmvdsXa3vOMXhMvkUdc+s1lvRoPiKaVKnL+Fw1OuPC8oS3qFzt3+5Yu1MBTOd9Vh2JbaYUCt/11K6CwRIe7pknKlOLGmyaXoqt+eqpq0=,iv:HapBGJSBGvNDHB+vEg05OsyCjCyqaWlKtzCX1c0qm4g=,tag:BExfVhpi/ITsp8NowB//wA==,type:str]
    version: 3.13.3
