apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:l7qoKHPIjssRsKFhGy0NoGSe//eV4oo5mOemZD0bXdK/XVoZGAUNWXq31CfE0RocQdN5w5RHwvIy64qe,iv:HUmPtUe5PEjB3LRHNVxC1wUG7bTn8owK3RlbiVHE6Dw=,tag:hFWu7aTloVVAnasti4b6nQ==,type:str]
kind: Secret
metadata:
    name: postgres-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZFpUTGJudUhvNDl5d3Nl
            cXJ1eHFBQ0VtMStPbUM3TlNiYkFZS1FGakVBCk5UOGFVMnQ1OTlVZzZaRDkrV3Rs
            TmtocVR5NjRkUFJzWmRaMmRFaTN6ZzAKLS0tIGlGQlFPYldCK09LK1ZSNWJyb3pi
            K283UG81b05HWU1INGFRMVEzdzNRQUUKZ04ydq6njUSc75PC9TFYl4RWnDBRlUI8
            IuBu29vBeitrwNrJ3GbIeFNX83kty3D4v9jZIBZaI02K7YRGqOOZgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:wTWNQq29IuROj4M3FAwe5OcVFE3sY1Lax6iTyjdcHgHtvJ+1rXUEh9gUwCxvTPUoNx7UTuGbiky2vca7aKKDYoi6bYBXxfQbNXvKNon+DndudUiuooEKdT+rDXUKbFgiIo5jFUNbsJkjZkcjUVUVn+ZnJugd1L+cO/AU9V79uew=,iv:keF7N6+IS3VhQF7FaOXR4se8sLmImFt0+ERLlSfxFOg=,tag:pwet0p8NnJtbfTK2gvOysg==,type:str]
    version: 3.13.3
