apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:owItfGs/IoD/0+xGs5Yjm31k7yq7PH7ZojYS0lebNIFKz7RK5IDo1+LwkdYjJ/tEOWoTZCgdeRe2930X,iv:31uxxkEzF8GeAZDg5EtHOZUUO+G7PFKr2A3EfZArAag=,tag:kDNl+Rd6y8BDf9Uzk6V0Rw==,type:str]
kind: Secret
metadata:
    name: postgres-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRi91Vm5HelpaTDZ2Qm5v
            ZHZZRE5uZStteGVFL00wdFptSW01d1UvZVNvCkJpKy9tZkNCZllrdUNjR2JBSUVl
            eEE0dmRzdXBtMzh2ejZHajBGOVVDdFkKLS0tIGd1UzdzajRpVFFQazFhY2VpRDRL
            aXIxMlRqckZZNXJydU5OaEhxQitGYU0KsB/lxB1VBx0YZ9G+qOW+B3Zi6lcVraX2
            1VZNC+LwQYm7pOSSZM8sqt21Ke5e5MaJbggsqtGbR2o7nbUoz7vp3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:1kpDEWYEdIEGNfIW3i1AMDG8B/K13FcXtrkYIDpCEGs69Zk7QmMVSk0kN+tI/5u/zG/2NEy36TvAhqx3crzih0kOqjdsZvrYici4nTQsYvc+xolSA8+xqGNSBJ6QRHuqEl253XfnWipvwBe7ZW3Dvw1Eh8DmSHLOhJ9YKfEDPsk=,iv:cXSU1odhseDAoP6RD7Lf0q4tL2BTgD9Cns0j3ArVCyc=,tag:q1y4nZcepID0ZT9UHDlJ6A==,type:str]
    version: 3.13.3
