apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LahWc1nrgYNmE902k8487+iRmE7snhbVFw1jKGrfPuBlXfyNMqs4rhmagg3VsaU7Fs3lXOnkAXyNvKsh,iv:U6WiX4ZREWLbZbpsBqqqoOXE9nAFvMooZrLvsiUs7AQ=,tag:TbwOQcpwRmy47H14td7CmA==,type:str]
kind: Secret
metadata:
    name: postgres-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbkQzZm0ydVdOYXBySmVo
            bHphR0h2aGMzTkxjVkhMOXdHL0NOMW5jZ0RvCnRlU0Q2bmhGSTNQT0J6U1dCWVZE
            aTVvL0hnVStvbUp2a0dwcjJURXlJWDgKLS0tIFZZVWFlcm5iKzRJSCtCd2E1ellI
            VDVxMjhiaEZVV1BtNlZybmVyZExBcjgKZCMqAadpgc5Wbeu3lZcdZO89j+pdyIML
            FRBc8Nh+pynozTg4m9VpeDEy1T5l1BSbx3XEih6TOdZMu7o312rrNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:57Z"
    mac: ENC[AES256_GCM,data:I97+D8wbwsvvQihm1aZASQbfoRFFL/zzn3dRxR3P9JylpCJPRNILRjgN5uiCXd46jJEXYuR+e8kKOCz8jq6HDw+La74iiatDcWJ6xktU4oHYoCJ0uD82i42RSd6uT6hWrxOmXTb+eWW2fNUfTLettLjDP6xFk4U7dATKaemK6rw=,iv:w2t4tR4lVqOWyytWICFgVhHyuqmOoPgC/leR/N6dJj8=,tag:D3MQs87JAG0ImqtKsnT38A==,type:str]
    version: 3.13.3
