apiVersion: v1
data:
    PS_DATABASE_URL: ENC[AES256_GCM,data:EH0mY1z2ejqNInXxWL9u6Bmv2Nlh8fTlY2H+tYYRy9cxKoiRGMSkWSWtvLNi9OVWZ7NYZjYmjlnrOQipN6tcEHgCdwGqr5A5cFcuIWh/VIkER1DPIpzYplTqsY16GnVmkhLgarqnjX7GIoMMpzITEQkgwX8zcUCTTW/rnUOF8/zHf9wxRouD7c8OBN8YKfrkqvNAuB2eDSwMN1Yr3gaIoKKVCCOrAhS1C8f3cQ8WbBdrGnNkYhqbQOF5t3AI8QjNoYufZN5PZyU=,iv:FIw/Zod0ka/+OKQY9x+wOiNfFFRXJ1h1sbkOHSVYHzU=,tag:wut3Nlwt5TfrYz6MwahS5w==,type:str]
    PS_SOURCE_DATABASE_URL: ENC[AES256_GCM,data:eJt+4+IiVCfyMXZaUlG0ePjq25rQ7NDAN5ShvuTlb2UhSAnugIAS0AtPjRQuC9H0R6Hu6wJvBp8ZD0f+yhFWk57vMYjfj4g6YxyB1GiMG6Re10lQBc3odLRmgKY+I/vRwoZY0P8fQXYNFOeviYQDE/T2CoifGgqkuOK3NUMljqSf02DeD8bQuwc8nLceYIuhtCwFwreJKsakVNao54lEFx4ogxiglZBfdJhXS5jftM+ce/cjMLl8z12BwMhTyiDz,iv:teZRlG2CerKqGQN5LK5deYw6rlMrdQIGWlTHYHvzxcM=,tag:PHm9Ia9wIFpQIlipkwCe9Q==,type:str]
kind: Secret
metadata:
    name: powersync-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwekdxQmRkTHlmckpoNDVG
            dkRzSm12ZXBKRm1GbXR3dEdWcHVDK051emxNCmd5bjBuNlBwRzJXbHowcWFHOWxY
            KzRTaXZxZEg0Q1ZVZTdtbXQweUQ5ZUEKLS0tIFdVd2NXenRSTVAwTEZCMDZQekIv
            TjhMWC9VVC8vQ00xTElJa0RFU3FHL1kKT6hFBDwgbRqbi26K78u/xlPT6RKCr/Et
            Jcj3+t967QWpKPveyHWLm7mlcu4HlkuYRxOX+S3Ez0GvvknB2+9Y7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:57Z"
    mac: ENC[AES256_GCM,data:4nezR51tpum1DfgbX8i4rpKsr2obyT4hx6tc6tRfa7/Bm6aQK4Jf/47XM+CAZNoRmzWxr7a7FKh4bOTdrtpNCEZPSYoEkY9P8HhfGc2VatvwGcP1iOAXzObmf1UpXCMVTgO6v8iIXh1T+uk+kiBF8hd2PKeirDSNfsu6iuGBfb0=,iv:oePpevpSxq812Ev07PIwz4j/hyNxyu5GyCxs47CGki8=,tag:1FnNcFyAPccBTRD/fWi0vw==,type:str]
    version: 3.13.3
