apiVersion: v1
data:
    PS_DATABASE_URL: ENC[AES256_GCM,data:meBWmWuFwfKJble6Bf8z/3bJzW2qjPZFiCnUMGDPu/4xwTjjd4HykcuqZ4Cd2A2F5rpHR/UDybhCz4HHEaJfESf99GorrzlpvMZUmBu1Sb6+sr4Ud6ktWSiYoY62HkEBmNNTo5bLJ4M7QQShgkZpVHQI+nQeG3y8,iv:hEpl8AA6ZGHgTIjI6qpUTZUJqj4kK88yvumyHnVtfi8=,tag:yPh0r4kt9L83KI7zWMsVlw==,type:str]
    PS_SOURCE_DATABASE_URL: ENC[AES256_GCM,data:HJ2iqD3RVzazk/SNw5ya0HUA7k9TpcKGHNNrPAllb1WlH9eoA1aRbjeeIj9W4qVx9mg8Myx9kY73iTIobKsxnvxWFkiqVTwbWRCKS0czP1z2r5tx0QW20CGxsqK7sydSAfDw4t8u0ZFfCSrrMNu1TKD+i4g61PFCddD+9x11Jfo=,iv:BpugnsE68yFYqTRvkeRSwcDhkjh0QiL8UFTFmtDsGMQ=,tag:mSgYLLRoHJSmQJfMT6Ytiw==,type:str]
kind: Secret
metadata:
    name: powersync-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NXFCUkJKRVA4SnpKM0gx
            NjUrZ0VTR2p0ei9Gd0xSa3Z5dDY4NktKTHdZCmJnZjk3T1YweGkwZGYvRFR6MjBu
            RjB5ZHBLaDF3WElpQitLSEZTdVZpbkkKLS0tIDdpSzl6OENwVzZRYVRPdkE4Tno0
            SjMydDEwWHZVYnIvdzZwemV6Y2ovODgKMmQWMFPnIAhUjESEqq95sYItogvvYLd4
            8QvvoWF19lTvqZdhOiZJDxF8v4670ygv0Q6g6ntgMfu252UyWEhrEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:kIt4qskqw7bs7xn6+0Um/NqNkKVsGkWaiMb67Fj7+EjgFGuuKgI07GHMazZrmYkTQfSRlXxK2VJOAJF+TUFz0a1ODk0Kx03Ghhw21Mti/vMt+sjpDhwiEHjqQru2KSuTaq4BsT0UcP7F1o4CV/WPOhZmUHJlbcwm8k/ILp2aFtw=,iv:90gveaHsjZU9W/hCLgEkWqbx2GnJR3ny+n3kPfi6G7g=,tag:8iYs0e3SGQin9P1/Q4vbmw==,type:str]
    version: 3.13.3
