apiVersion: v1
data:
    PS_DATABASE_URL: ENC[AES256_GCM,data:6d2viE4bVoQiZPRKB4Ad9TPzovFsDzkWwLBtjE8ATbZSwP1QUOQ4e9XcMU5sbIuOp/WAr0eFVvzMIOcsXJbYzuoJ6iF1AINZ7cRFUkTXmk2lFsX0DoPkDXCXWNrRenrz2AvuXzRdqcxadr4OD7gcKsAGYHV4WE+9,iv:TTUVO4Npek1NAigiQz27akvehUfNSPoo7E2B1D6WRqo=,tag:79JF/thy+3FTtcd1J8gmIg==,type:str]
    PS_SOURCE_DATABASE_URL: ENC[AES256_GCM,data:MsbvJohF1eV6vTvEXjVUnIKV/6abUTKyNmMyr0kzHW48P70Q6xDaFdLgs2orwC1GLEvNPRf1uoI/pO/D7GkxiKeh5+WIO7MSweuPokXZX0YOl78DGxPx7GggzG6ojiWEc4wf1UUepylGhiY8xm5QFX17MvUBiFtcQx4S8ylsevw=,iv:g8w0quxvirGKFUop4GL9HlFQChiBUFFoDuQmnJinSQo=,tag:E62QiyN+1dWbfsbv388FlA==,type:str]
kind: Secret
metadata:
    name: powersync-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWmJkTGVOTDRKbmxkeGpo
            MWM0V1N5eVFYbmswb21IU1cxdWxWQmFFdDBrCnJrdGZya3FzaEp1T2ppSGRqRVBl
            L0hZdjBKL0VFenVNTTFpNzF3VUJvU1UKLS0tIE16QmswN0VhYmlTRnhGbFZZOWdJ
            SUlHNytMZGM4dUdrczZsbjRiaUh0R00KSQgF9m7x2GsvagBy1Z+Zi65LKUHQjFmF
            OT2TE6T9q8GmY7KOi4i+qXYhWYGj2pZMkrkwS8HjQ78p3+FWofIl3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:kXw2lbAC5o3f2yU7OjAwJYDIcYGg2Kg3+J18uj9NLZ+vilfCcMsRNaKFDBk2n4FQlszhjnvzKMw1NoGFDEU2seIzQ8sLIDfUR8N2432vaVQdMLne5ezLX++RYYXpekRwi4vVGpupVovQmnM1nXHyKGBciR4Hiwz57B0F6Or/e38=,iv:1UweIifMVMrFwGO8g6TyEqAI5J018O9Mj2/MmGmNt54=,tag:Xy7Wa9rbXT58qG+WzZCmqQ==,type:str]
    version: 3.13.3
