apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:M9kdLkIJBICFpDKMrBD1xw==,iv:LVbqZC60aDl957RMlktIjOsBvHuwSpFgKCEOPT7517Q=,tag:85ip4Wkw1GaRI8iWqHJWnw==,type:str]
    ARCHIVE_MYSQL_DSN: ENC[AES256_GCM,data:rDHBcueCONyKPZH+zW87MHqX3k/qzBJqs+uMKQkNwGPXUqqadPFwjNPlXw2OJSz82xMwzdvaCvlpUXQhLIMplIBjCSiecYFSNy1sMal+1iDoLGzx44WA/XEK6DN089RzbBJSzqvqiuCuIgvsr49w/g/20eE586Eo85W393DMIdJCz4VdzgamvcrNFZzL49bkbhRu8Q==,iv:xFW+fI1oEtMKdeyySVsLvU2S372wven5GOpyfwnZYaU=,tag:u//l+meg73qqAw5lza8Liw==,type:str]
    CWA_API_KEY: ENC[AES256_GCM,data:uorIgLGLrJX7pEko4d6+xI/htOLFEiGTUrpfUZwtx1k0Tnue4HBa7bO6cFBT9v/IWLcdG0j8964=,iv:8Amoc8QIPmTwKxM3Ln80f9AQEAHuiP5qZQ5dm7Jksrw=,tag:MDLsL1y9G+Y4e2bmFCvosg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:b+puUnPRAuyo4YfWKovCJfOh0QV49ToZiiVcHgb/DudgkFCx/+xoV9d4FXEatMWxOFPU2QdGtf4Nly1h/QAWZatQ+1GngAMKA9XmkSdjabB++eWrREAGyYlJzdpHGCA2S6CjaJzCUxzfvbX0+9oltl6+VJ4p5wKk,iv:TAKJnVKCwj+t3qS402Xbpseq19JZnURIKMFBFWqp0io=,tag:6fQJOEG2wcErxrZbJrkoWQ==,type:str]
    FUNCTIONS_DB_MAX_CONNS: ENC[AES256_GCM,data:Pk5tCA==,iv:HAYTRm/uZfK84Nwcd1tkUZ6ZFLd+B4PvzRhnWa+MTvo=,tag:B+OX5fU78gOG5CKoaQVNbw==,type:str]
    FUNCTIONS_DB_MIN_CONNS: ENC[AES256_GCM,data:AurLTA==,iv:skT6l2K1XKwyYoo6QE1pA9EJR40CddGbo3uoLt2X1m4=,tag:fbSXQt/Wwma7y7EIroDeVg==,type:str]
    MQTT_CLIENT_ID: ENC[AES256_GCM,data:FLiDNf4oYu5Ai9kJ/Wb8qP6TfKrayNuUCMsp1TlWXamQjBnc137lO7TTctk=,iv:Z8lSb2P41mniLKL3reWq+4hMxZqLSyxHf1UO4aCefAM=,tag:IomJIoZZWngHkG9GCllINw==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:sAXYxSq7HAOfokB+gAsoNWV9lJ0EnEAmnult8ryPTHmq60Gu8i07ioiFttS5VtVT,iv:d3dYMZCCjC5JfGYk1zOZbfNnXy1HNCOsr/9f1nFlKK4=,tag:IlcYuicTkeg6P6fqjvDvtw==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:aSPs04R7G6E5rkWhuyLREUFs3PcRRyK/L7PrwTy8ob7BCmTQ,iv:dwEQoJPxw+OuVrL4/cp2mvMc1zlT/a0fwJZg2Bbj7TY=,tag:fR5U6cEiGuiNwfS5w0P7IA==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:qqjRGfiTB2k=,iv:kLmgA3APAuHeNXDVhvNfG6BKG926qnNYxOFUiH1LYIc=,tag:dGDz8ZTpjlhDYIUYIAHzeg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:v8l7JSA2H6RtER6t4fKecMgINcvgCEoxxG37OfJeMsfLsNqoz0aXIVOAauHP7Qu8+YlKugVVw7Svfdpz,iv:TnyYYEw8kLTLh2AwwBDexXa3+/rWm7kuidiScdERltk=,tag:SxO46u+TosHwX+yuuMze9g==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:dhmIus7vb82EI0ZlHyU3WjONIR8jIUkwy6sA5xMtGbk1utVgLXIgRti6Li7BqnIG32qcW3SdghMPKugje9G41W+s2AjcX0k6BvXtEaYpBzWv3Hf/XhjvD8lJtFmWOrgqRO1u/Rm50/pAEtv6C9J/dYosXV/Wz6rDEmQo0vOuV/4=,iv:eYc7pNFmQxrtkWA+Q1hAdXKLkZLtPmzEWLpf24i9E9I=,tag:F8URR9hw1NCqGdetTVeVDw==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:AbK4Fe8TGs7kINoO8fWvyA==,iv:8sc9FRd4dgpEcY3V2kMKTLFIl7IBybDp94jHKmPt9F8=,tag:xEDPLvMp9dPkjgS1y2W8qQ==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:HQ/qUA==,iv:J4vo1woxSCmDrnnIF81RLjmvlMLpD1NQGURNAKTD8d0=,tag:QPbX2PyNUJG+od+hQ6fV8w==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:1bn3rL0NW+X4nXJZU+cv6L+t852Kzp6TwnzAAhhHEXoXWj3P,iv:QEygPfolWD0olAamoQSQeHGwCHfgi9INqcTWxLCRsdg=,tag:/hNvsFwhVBgPMSQgUmYV4w==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:WKJX9ZN3WI7waCLwrZuiio4xycWUPCkKdXRAyXJ/E5neNCEcHl7AwDjjx4C6poKU,iv:JvbcIQzzNXfgNhN2KswDAE5fAIlz0QZsZxfGabwXk7U=,tag:XtKhSTQaH/dh1IBpbliBow==,type:str]
    TRTC_PASSWORD: ENC[AES256_GCM,data:xGR6I/a/jZGvqCuWRN2Xcw==,iv:6UTNM1vNQtiqs20WSR5D0RU1TkBGvQ6ljAIToZU7HLY=,tag:qAF4POuRrG3Sz/ODtH2eFw==,type:str]
    TRTC_USERNAME: ENC[AES256_GCM,data:B2mlN/qSLjKH+mR5A34u6Wp7MWaciVVimoJE2lPtjpM=,iv:xPUYlAZ7iAXXW78NTwrd2Suh0VulVXwqW6kA1R17p3s=,tag:vOJuBKIy48Fyvi9+FlNRxw==,type:str]
kind: Secret
metadata:
    name: realtime-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFM3VXUVhLZm5vWGJVak5m
            V1dpM0xXRno4QUpReFFtVkdOM2Q5dTlTT1RZClpIZ011NEZ4Tlp5Z2FDc3BRbm91
            YmtaTG81cm9iZFcxUmNhZ0V6eXZVYjQKLS0tIDRYNDRlb1FiWEI1V29iM2UyMjN2
            b1RaQzhZNFY3dTBQQ1RTbjIzd1VMZmMKT7R5PumEXAoSj1n397l6ZUtHfqkjGnet
            aXcbfBcGysOq1KAl7h0n9r9YYOgCeqzrgqrObO9KG6vFrEQ11B3vNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:L6vJ5qMwRSskRjdFKyVoy4i8nEIP/9y4Y0LAFGEmp3r7aLV3B/gdOaGv0iEI09hU2uYltPKaOYQS/HNqg3NGI7uos2k56oLuutuPtLBMcPcJx+CEqM/Jay4yFAmuWXLZM3ALvPFPcKehAeyKjP8tiTuFcdrTmJg5F5KfPVPiXzw=,iv:ieJ7BHv6MaIWhohlYsoTrxFIr7Q4C5rmtW+vZC3rnXA=,tag:99xWwc8WmHq9tKNdMQpcEQ==,type:str]
    version: 3.13.3
