apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:J4rKhozDoKrRQHdc0QZLHg==,iv:BDnLyL99IS/Hgg/y8wULLlnNe7q1rijI0s8RfXQgZeM=,tag:52K8PSOf26Y3VF6ghVFdAw==,type:str]
    ARCHIVE_MYSQL_DSN: ENC[AES256_GCM,data:2MwIwEPzbFWUpdV+5tQ7wxCJLArRYPBatlMg6CuDQZZrV4Ru0r9+v6WOBxl0OtCV3aVpt0PwM7m4DFrYGwgbLS0OD77H0j1wSXYUkdfjtN3xmkMlJKmWmrmlneCq/5WsYVb1inZPd/EAoVlF6ua0pXRF9wD8GWkove6Suf6mTAcRaWGI3yHLvQLqEAc+Kctc1kw29A==,iv:ldhSMc+yBJegDAH9cituYS+e5LFbn8V5g8LWBeb322Q=,tag:W0ZfyGRZlyPQImWlYAmsuw==,type:str]
    CWA_API_KEY: ENC[AES256_GCM,data:d9B6ZT8OtcpxJOQk2e32qcxdIkCJ8ONCjd2Ib2tL1aWFaKqpDRCrIHVFt2a2VOhgr88Xa1/3AuU=,iv:UoaaeCmKoGigvpq79iQZ4NItbec2QfsssIhClkXl50M=,tag:6Fsuidx4XFR5N2vBTK+MIA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:3zsrvkvEKuBH/8pDa3QA+75dCjfTbla1BxPMi45D+CalNjawj6Y1chmtCMYzHtsyIYlZd0myxo0GExWMXDOD5Glzfqw7necPr3a885m4sZkF0plyPGyyUF710tDtUZC3mGQ2iQdxVktd+DzB7mMb/0KeN4QacucsbLtSq5jMEfwpU3WIeV3BwTXFOk3LbSJSkKkMHuJG7Qh4Chdeyq+AZFLccRSp7CwXKFEL5WNOt0l2Kf69vYm39Ydfago=,iv:xq8XSkrBFSiHE3P/C4wa173Kvzvz0puRKxkI0QXP3rQ=,tag:VvaQG0AmPfG7eVv272iA9g==,type:str]
    FUNCTIONS_DB_MAX_CONNS: ENC[AES256_GCM,data:qBYLcw==,iv:CLZNNcCIWlQ5P+iZowhzc/Ep0zq+QbtmU5otxa0HmuA=,tag:KIMynaeCXfxx+8Y0pd9+vA==,type:str]
    FUNCTIONS_DB_MIN_CONNS: ENC[AES256_GCM,data:mIX6IQ==,iv:qiteb/k7kE4bgRQcHTxw4zSWXwu0ZOusJkQQ7+RqGRI=,tag:HcjpPtLdB4NgPBd/j7rmow==,type:str]
    MQTT_CLIENT_ID: ENC[AES256_GCM,data:eNawMVZ7IBQnOOQpC7UpvnuyYu6KmwgcyAwgfCeTuNdhFaKg/rGbJY0U8Eo=,iv:6yqG32upiHH8CrDIlKwGz3/KvfgTH2pljE5fYjjEnYQ=,tag:rD1c5dTYf+G6u8RJSlvAVw==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:4SWMVXcnulcIeF7x2glJm5fEbSWs8uqr/TAJ1j0D/JRPseyFbT3OECfkFzUty9zQ,iv:bDRKSH1TZP4+Xsm8IP3jqGr7AMRQog6436KEsiogbbQ=,tag:fZG8pHXLXNIG9nMKvjhqeA==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:/ULI2RQnCl0gAq0BIJhNn69a3iSimiBDhB/2r6PK62kRGa9H,iv:mAatY/sHJwLU9A23JZM5jIHzIqQukEni7pFiVAZISH0=,tag:0lv4MkjqiTsOMZc3zAwbUQ==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:zoEL7RELsK4=,iv:eOTz9o7CQllz+GR5Pab0ln+jBbLCIy6EfT2fstoNBQk=,tag:n1NWd/q9PcojRGFi1T2dYA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:0bCKLfOEFjdChKyS+1FRsHAkMDCAuOQesJkYr2Q5ks76XMVSQxD9P2MiR//8xcFhoJFxxxj3QcCLhYBQ,iv:wf+lmTecSrqzSIcjyQ5Gj/hLrNropcKSKj/8mL5LjAQ=,tag:LpNDHwLcG49qwjjmdL7fxA==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:JT4lUZ+RPIZo4pmWp2ZgK5tuvN8VUDvW2ESoeNaN4G8RX76BI47KlA3bKUFfGRIIi28Ot+JztCsBfdN416OAzm4Gqeh7jm9hQNlXXrlzgAr4jmI9AnVaL1HDbASGoBW0ozK+l//zVgoEqzYnctJ4m5F9hog8+dbeBCDeLapDMms=,iv:ZnY1zc0qzxmW4C6fEJ1j5OMkvG8IS/3Osc9mjPYf9qU=,tag:eDWZvn/cHz3UuFjjsD6r/A==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:HahvZywAn+jLt0q9EvBIbQ==,iv:PO75h0XftvkQmAm5NAB36nNjnWn3WdmoM5Q3q3SHJNU=,tag:+DG9azllbWj046L1EQK3Yw==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:ZIr5ZQ==,iv:WDQt3ddrnhbQ6gFbJGr1Q7no23DJQ++7ht3bBJc5ato=,tag:T0oSTezqtKppKoolyZAKKw==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:DVA36Zeniq+1KzA+UKs6qJ88G23i2Ra4AbYVovJ6bXKpdkzK,iv:Mi/XTJ6FW0n3CyucMUzHTmUS2ov0IBMvxnvkeOnK9BU=,tag:YL2asWlXMC+ILD0InHqsYw==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:zGvpGCyaOBrVINR+/7Od/+Qc2zB/qJSiKft3Y3mjbWhgsgEDw4u22FqrXS9R/dO5,iv:zewxwNAk+TqUK5XFNW8Bfv7h9FCoVYfdKMMSSRXc1HY=,tag:5RMdIPpR3LXHjWGIURf6Rg==,type:str]
    TRTC_PASSWORD: ENC[AES256_GCM,data:jQkFOC9A4RJ+wk55fSxkHg==,iv:oEFf3k46UiH9dEjIWbCkYSNN+VwqikYDhFhOtwD/2kQ=,tag:Op663JUDxWJ69bNrGdAxwg==,type:str]
    TRTC_USERNAME: ENC[AES256_GCM,data:pVhkRgW11B2YBHaNbEdD3KVXynULZB7MCDB5alzDu5I=,iv:FKL2Lgjk6yBfUFzOEPCJAw6cclhh58CU2kNLuDgn9Og=,tag:cfd7OM/DD+NXefd/Rd183A==,type:str]
kind: Secret
metadata:
    name: realtime-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcFd2bWVBbklJZXdVc3M3
            L3JjUnNLQSs2a25XUlBvejhSSDd0RjA2VWdFCkF2WE5mTUtDWGNrWFY3TzlNYzhp
            S3ZjTUpvWkQ3a3gxYUZBaXgrakZ1SmMKLS0tIDFKYy9WSlBsMmlFNk1hSHNhbGcz
            QVByRVUxMm5UeXJpaTdpVjRCY0hBcEkK5B+gCXHboBJU2H2pC3LdnG+7yFuB1/GV
            y79oe/8DNH+4ia1qIHaZRNce8dwuDYLai7irFmZnT52WzfRHG9nRiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:57Z"
    mac: ENC[AES256_GCM,data:kR1uRKO3/2bK40wPMOlqTveZvuaL/be67FUb5qHPmYRo0v+NDIhPc9KLqI6tjHUTk3xoNoZjP8jJFqCo9I9Mda/VK/r5sPDwhr7TBSYnWvGRVmf5jq+p28NZXsw1W3KkqNEadhnWFiCVwQPLG3MjB3djftDJOszaYaQB/OPfjjQ=,iv:63e8aWybAk3UsjpNLvfpzP+wYlamzcViVTfBjml/Ld8=,tag:CnLGpi50CzXa7f+Pp1EHBA==,type:str]
    version: 3.13.3
