apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:l2awIhGfQmhjHFcvhOK+/A==,iv:aYQqiSGJbmd3QD/G5fydNkmtprPR5po+dTbAtyy0LUs=,tag:hx2z4a5XY/X5oyNI+slgXg==,type:str]
    ARCHIVE_MYSQL_DSN: ENC[AES256_GCM,data:+A7lE6qZhFxhzKU68tBJA4Ov5O/tDkabBkUpNiMvXKHnwFCV3MkNPgPtLTpl/Rt/RdgJ0Xztg5MyjFPbberFfkA2psa2AJh3Ks0BV2nvA4J25QwRRDICN1V1XSVC3jz9GnCpQ5bviD4vMKbySsf9vnRqxUYKfAmssPfKGoMhvFAv509HZcvlq7TbFZJH7Bj5cLMlXw==,iv:IZe62ucCnTXg8tIUr3ez+Kl5VobmW4QJ972B/yU4ogc=,tag:oeyLaRoATqZm8kYGqpNgfA==,type:str]
    CWA_API_KEY: ENC[AES256_GCM,data:IuIeZq1xLEnmyZ5ILI8KV5xaweEX3EVOGNioQ8aTnelIavQnDJjuqQYl2XIgIer8nk8psHrn1mQ=,iv:f/NWI/svrzgqGRPKSgk8BEAiT+OJB7aruB6cpOLkwyU=,tag:a+rmoVBsHsAMKe1PlHSKpA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:j57UiR8tZaqJghmc8pdPs7180zkv2OALdSbVco9MGQlSLc3M+1T2rR3M83j0WA4b2ex0cgQJcz8sPBcnb85BWsRkJowCzwTpcBTp6ggYyjoraY8HMXZvZkjhy8G+i5agYC3/J2I8JMI5udKJPAfsLcFY6xn1CpNu,iv:VDszezI95/CURuJzp+3Ar1Q+3fqM8ksWgEcjajMebiY=,tag:A0tmkN4LlERk7jczmXRskg==,type:str]
    FUNCTIONS_DB_MAX_CONNS: ENC[AES256_GCM,data:90LcNA==,iv:AWACEIGebRQ/dgadm9vmHWnA1RNO+MNsI9rypN8TEts=,tag:Bh9V8tzG271EXtq2NY9cRw==,type:str]
    FUNCTIONS_DB_MIN_CONNS: ENC[AES256_GCM,data:fQQ4Vw==,iv:VkXAN26bYSpabcnJ0CvybcJ7pI7uaXYIrQdfHsp8oDU=,tag:U0JEjIg2QRwzM9791KSOEg==,type:str]
    MQTT_CLIENT_ID: ENC[AES256_GCM,data:FYweoK/74QCvpGC+RuprsbPRRZW6hgH5YEDXKafyNLNlw/G7LMCcNOKLI4k=,iv:zuC/oVZuUqLZplifo6c/pJkqaiMC2oPRWifj7EOoU10=,tag:nyKwUx0z6gwail85GOfigg==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:MHRr+cJ0GCnHMWLlyfkOAj8iiG52WkCV+mpKtgNa73K4hnh0fpXjd1O8oQKRzmWO,iv:2ff6oPIdm2b+AmwOaYubxaQjKiBmU+ahtY7Zia/u2ck=,tag:sqp+WK8DeMyLQeh1Qxvz5g==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:zYYJch+oPkNmgQbLytfBBvrGdgphSFFbsZ936/149+94QALf,iv:aL8p0lpyQ4u/124IHIkCEfX+ygCvSP7OfcH5I9me9sw=,tag:kmaYbIMDAc9N5gymCffLzw==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:+av/Wi7GX0E=,iv:PypvOiYN/be80pTprrFoLN4J/T7u/u83si19beSoVTY=,tag:rxxQ12xW5klV404OxPV7Cg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:+XXMhZQT6WkcWyjdntNrniRwEkTTGe6oYqx3ML011LWhOmTakMOiuzXZdfVXCYmGlO63bj/Q38fStDHR,iv:813DKOd4KmIBtU2O/crSLy3E85zzde0fOt9jvhHPyX8=,tag:V3FWk+pgIM09nRGN6wVabA==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:bQQ+0rnWKWw+lAYeVX9v/VdowvKQ65LatJKtZs8K+OXY0R6qlRW7Q6+cQw3sKPSe0Zrnv1QAoA05ps18Mhh85MCpc4/VEOBaviLjuWBVqFdcAHqX91JmkJxuFLquuG57FBtcxJ+j349tDzltcjKykkYkxW71bfvIhC3f1sgHIcY=,iv:xcef26XhZoxCdIoQ2FuZFl0dEVIRO5GF7oCezn3F+Sc=,tag:ebvudzEYcTiVeQ/g0P3n/A==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:zM0yq5oCKOFeBnnmXSoDIA==,iv:s7EQWMCEQA7KZtTYQwoxyqGdRk5R4wRziVAMgySWl0c=,tag:i6Dvc/jJHzEhUgqLJzh7HQ==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:1pUShg==,iv:CN7WAvgLxtJbko8wECj4vWwKsYWVJpLS/lBXUuguPQI=,tag:TGt2a1Yw+2g35kTQ2qUg9g==,type:str]
    TDX_CLIENT_ID: ENC[AES256_GCM,data:iVCGppC+YH1dlijXGhb4FKvFAExnN6JcehKlFlnKMO8xJvdn,iv:g9ssJdH63sxDWz7Wx5pl7VFNidOaLb8f88U3Qepqnkg=,tag:0XXWy/zMutHmcTWdUsONxA==,type:str]
    TDX_CLIENT_SECRET: ENC[AES256_GCM,data:x3OSjGYkWS3crph31pe6Wtsf0Qja9J3rFBUQQWdCXutRLmDVXpTiG2jOz/aosnlE,iv:XzLpaBTSBNlDYG6OH1zXbrnljb4Qcz0NZzAcGxqdDds=,tag:U6K26ArMa9oGorN3Oli1KQ==,type:str]
    TRTC_PASSWORD: ENC[AES256_GCM,data:jhC33rDO8hsNh0ZPRpaP7A==,iv:dduhVFQvHu1oiuNr2z6c7RJHIYaQL6c/h3HbEISSMzY=,tag:NitSsKfsz45L53MWWehSag==,type:str]
    TRTC_USERNAME: ENC[AES256_GCM,data:kCNuF9xxzhOHKYL1OpWL4BzruW/NygFbeX/EptWpBOY=,iv:TXisYUpOMVsgRBYPHFIw/I5CtOU3qHA/uwf7aonJHIU=,tag:O5rkkhatFJmWPc9sUMrlSA==,type:str]
kind: Secret
metadata:
    name: realtime-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySU9Uam5LVE9VVEw5YTZW
            cit0NVJmdkF5SzZsZDcxb3Rkbk1qSFRQYW40CmovVys4MkZsMEFnNVJpbCtJTURC
            NFlwNFRTZWp3VGJkUFhGRnBDdjZna2cKLS0tIERDZFM4aytyNkkvc2VrSVNxWlA4
            ZEp2b3Ntb2c5MVNjeVJ0T0VJakYvSGcKHEZ7HCactNhIkPCSPBVGtPVUpc/hZXvp
            /T+wH0Mj3PV5lFwhfUbNJlcGVr6eElL/aZy8vFNp9EMkj9+D80qugg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:w/IuDOEMcHeFIiU/s/vkKiblMPd98jKiVQKASGkIretXU7t7ipcyH/pzi6EZtkjbpYwcl6nkIG4A0tZpxrUlQuRajs5auWGlTZ1Sj230MBLDItHQKTpSN2L1sdbb8q6fjGSFmTooFWHkVeGb2RVH8UPKNUVcOh6EOuBblXjsyRs=,iv:C5WfhJrnUqHwLDOE9JoBkALgqPaZnjt/7JL87W63iNw=,tag:M7aAQowdAAKtLivdOyzoiA==,type:str]
    version: 3.13.3
