apiVersion: v1
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:VfO0HEYE+ieRjm+ZEx8kH5MDKnX6FMU/bF/BTUJ43Hl07/13d+gpxJbWfmgrqTkFEUlXs+E8cLDg8B7a,iv:mUpdvdF6dEcifF5Ieb4SnmsMkQ/ZyKuySYEbvC8kyZ8=,tag:95PN5Ti+0gU3vXv8h1++Lw==,type:str]
kind: Secret
metadata:
    name: redis-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcXF2cmNmQmRPYkNNQ3Qy
            cTM1WEZsd1o1cU9PZVc0SGMzU1MvMkxpR1RJCm11c0VUQjU2MS9aUFJxK0dmWTZ4
            RDhxdlQvUGk0djl4Zzg0T0hIZXg5VVkKLS0tIDVLejFXUnFmcFpORXVZSGNYa0Ny
            bE81aGREc2pkcWM3THJYV3NEcTR3NWsK3ly3WT+Amo39WHe+k7P35vy3rhy9zZkw
            IzERzAiSU4AueHTopeMO6bZVEKWjQsvKUsKZBu5rJVj06rrv+gqRnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:57Z"
    mac: ENC[AES256_GCM,data:k+J46Pq7sP+jWZ+dcErXAaT5j7rWDVXk/NSgRid/vi/LRbNprcAZPXF2pJ2/eGla2aFlklmtigZPTBDKHYKT8bf2ubVNCbsLsdPGoust6qh2qpzjqy+6Mp5UbYH1ecjNMv112PPcKwG7xZCWMc6j+097kkxM7+P+ZKO92Tsplms=,iv:gpw959bHTlN6tl1Lisf/eM7c27n+vsqE+fdZEBrIpPk=,tag:9CsOPFo0FuUQu9nAvZU1Zg==,type:str]
    version: 3.13.3
