apiVersion: v1
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:k6bAr68bOg3MMgP2hW0bpYFiwqRiIxryvoLz51PBhpn3bMgAKYwXroezMJSDt9Yl7ED4drtmH++U9HI3,iv:BmgncIc3zcdeQUodFAWKtlZoTw0TtTjHxAPf5luU5n8=,tag:5PSN4PyDGRgK7KKar0q3fA==,type:str]
kind: Secret
metadata:
    name: redis-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYWJsczViYUZDdUdZOVdR
            dkF6Y1BNRVl1aFRhNnkxRU54ZWx2U0U1REdzCkdIS0cxR1BnRWtBcWJZZkc1ZC8y
            QjhuK0VLZFJVNkV3d2RLZzJka29qd2MKLS0tIDZoNkJ3T2hhZkQ5bVFYSUJmSkRk
            bE1wbzRQZWhIcmUwcHM0Y3NrQ1VnZEUKhKuXu2aGbbdSyPZI8BSVmdLxwXtiR8Zb
            mn+5IYZOqtCEv0EBL89iJ95VB1YSnVbGMbZ7Bjd8NzCzY74ns2ErcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:p3bRPpIixhu665QJub/DghyePxXMG8ffN/ZJhOysYWGRV3v16lEkXuKuwZ03e1tn6JQpM4+Rvzcdw0SY7R188tYVPfMZaWyBk2D8WRLFszFhv0fkoyQH9FU/FJ114RUZFcb4k8+NJFJIfLCkGeDFM+8HBw9veP7kTxpfb4tb8W4=,iv:/mar2H2f/a0hBwg+iLchw/8s1lqNXAdrqXlCM+wlnRo=,tag:+IPl0KA6EzZo36fZeRQz9w==,type:str]
    version: 3.13.3
