apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:CNo83cfuDB9kIbTETeyugw==,iv:j8zrADb5Bz/oc4oYO3DNsN3yilpJxAeXfYHT2pgDNkk=,tag:fbJ2VLgHLER0VHifV/Q3DQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LgP2A4uwPe7ZNmfMye3v8aZxRB/z64oiIyQbH9gbEe/BeseYgtZpmYJACJLaKRtfyAN4Yu6pkvg8p9iiPuFu+/84vm8KWaRO6gLTVp/JSiNX4kSe/4xo3zr5WQiFuERKpBE3CrR/n6PHibWYdtA553kM5aUm536eJxs3rKuBAG93jwnWVDLlDBu+OmZOu2P83W6IjGFnqQFMkfAYVncckrUBLkihOb8QSADVapNi/ekdKUT4kW3PNQ==,iv:8rkqBxoT5hxI/vbdjEYPAax9sTS+WkTR8WruQ0Jj3S0=,tag:oUxlifzZufMrq5IVzxw/8w==,type:str]
    FIREBASE_ENABLED: ENC[AES256_GCM,data:gAgIXmsg4yU=,iv:pJjWQ8F8kK1c5IScFxUvbpuGDoj6i29P44MigVhMYUs=,tag:f/uJ5JJfxdJFPhQf4eR6LA==,type:str]
    FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:m/DUbuUCu1HX/OsNLu+fRw==,iv:8tmZKVz0yMrwS9jXZqwBqu3frtZoagkW+K1v791W00E=,tag:lwyquTxEz7JsyfZZLFyDbg==,type:str]
    GOOGLE_APPLICATION_CREDENTIALS: ENC[AES256_GCM,data:QfndskqwTwzz0GfWrWhr6owYoX74apos4tsM4cGsHR0oTpRqzxWexQ==,iv:x/lxCxgGAFi6AjVTA4MeNFPgvmb4MKf9KcHoF06ENQo=,tag:AVo3QzFus+2ySa+y4daIKA==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:9feyS2sgCQw=,iv:ABlmYZE9EYhaW9vLvhTjCKdGDjsKonrnw1kpiZMv/pc=,tag:lQEUTYDTbbeqV8boQ4s7XQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:zsnh8sQX2+x6lMWvDarR2NeMOsueJApSetFTdHeGwazEuXSSOwZE0MyFwH0wkW9bsCupPO0gnUtJqF6W,iv:FX5cdZgyP2oMYmmkUFtyGvK7X559pnVcs/buaWz0MO4=,tag:TRnluNQ17lJg11dzJdIHIw==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:Yp0mRRI6VNUsMWTcQfIb88zxAuuG8PcfuYW2ToK/ir6pIpsOhxQ+C1RGAKf3Ny6KzhIkUWneDfZzKcs9CIfH3H8tstoWWanqf1O1PZNjr7ATmDTFTFT7sVWrziZw27EAYlxhxKa3OSYbpmsFvTvhRUpWjYzb4jptFjEsc8xXq38=,iv:CcRUeVrYCe1BgMNNO0FXDz3OGcBBezPKfWla6imHRxI=,tag:Z+HVw512DbQBNmi05AyjzA==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:V0GUxI95BwCt6C+KzHb60w==,iv:yN4X3Qo1ZzeqQ2oTNGC/FVfCPFipNsMJKlgR39HVO74=,tag:0cGjhuFCcombx97h2YGwxw==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:1L6Ogw==,iv:FFWXk5kIuVyYUTjsu9dRdkFN++4GYPt81OsRspO15OQ=,tag:GaSbaM+gtg74i4jWHi/7UQ==,type:str]
    TRTC_PASSWORD: ENC[AES256_GCM,data:tPynYcQuyFDznaFu6NqajA==,iv:44pV+hVkSS+Nlm614I5Chn+4fice/iUX9NXTyCD1bJ4=,tag:68cghAYB5klHyZS/JnVS5A==,type:str]
    TRTC_USERNAME: ENC[AES256_GCM,data:rd88qvVmQVWlZfmEv3egDhbxC+NFsAaCkZprCQgpgqU=,iv:qK+64OWigHuF927pJdrN8o1B8zrroPdXwiRpwUB5E6k=,tag:2abqYsQypT7NBCfGWaiXdQ==,type:str]
kind: Secret
metadata:
    name: rider-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUzZzWjhEc1R1cFMwZXRF
            LzRPQU1MUUJXRm8raFl5MXV2WHRESytEcnhRCnZWc1ZpMFVkY0VRQnB6L2NwUmo4
            Y0hoV2JvQ3JEejNvSzMzUXVZMnhDU00KLS0tIGg5bVNybk1RY0Fpak5YdHo2STJM
            THhqVEU0OG11SlBrTEUrZ05GdEpWV2cKRE5+ebSxSrcTYaDTvZQm6GeaiXWUznip
            kDeHvBi3sso7J8u+3WBjJvcTrPevwpCRNe/v7Im+LnZA4RMjyYK4oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T07:15:57Z"
    mac: ENC[AES256_GCM,data:xeQzqJm0aqOcW0SsRLKEwnH5DfrzFK0fKr667g44HWdPBtXkpypLFpPsMWE9hMG84GSHIs/sfmwTkbJ0uMfquSnO6LVBedEchlTUNEt6+9cmvd0ZBXSWiPU3Vx0LXMRp1dIbzyEyT6zgOvEeXC+/oKEy09vJrCY6Qn20/Cfy8go=,iv:sTD/dWu2AL1bgGY0B7GelES2YbbP0lHmXJU34/XWwDM=,tag:A3mqSkDvAnuZlmI+uzh+wQ==,type:str]
    version: 3.13.3
