apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:9RlZPEERKuDKq8pJsfT7pw==,iv:uxVSOdun7v+xNc+TRn4JCNBVAjrqB0kUuaSfu/7cl6M=,tag:H9hKBUCTCtQFkDXgQ8deww==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ZavEmb9MNcChEvUfFuSob+IKzpLNjpHshWnHWhLrGQ+5VQp3w+z5w0yLliirxnKbOy0QxTQ8wjnecmOhAVMWwJSKixq1LSwwaODGlb6lHLhQnmFdQb1kCb3jT7cKFTtrRxmw6YV8Y5J5Ict1xcnmAbhmSjMmb+Ld,iv:vee1uxF7OEp90b4kIR9F/nt5Gq9vWcgha+DENkwkOvQ=,tag:Fovs2J5QAu8o/xM/vWr81Q==,type:str]
    FIREBASE_ENABLED: ENC[AES256_GCM,data:mwlA9X1QA2I=,iv:4CCVo6B6r+TK/m6oLnwSUbkadGApLi0mjCAro1yO+qU=,tag:T/3h4k/vmnCEBz/yAuwM5g==,type:str]
    FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:XKxEfv/zcQrOtjIG+IWplg==,iv:ixmNHSNk4mhAWkWcme13IVTd/V1J7Cm/5R5UZvWkbF8=,tag:5F+PgazBtApdJoWzn1Vq1g==,type:str]
    GOOGLE_APPLICATION_CREDENTIALS: ENC[AES256_GCM,data:YziKgPlvCBy7kxzNHzH1xa1rRamHiB/JmWlXa/gxAdpV7qLZOGQsQQ==,iv:Xfg7VGZv1YWWS9rhsZdRxuTDfc9B2w4sToj7RHg/ZIQ=,tag:70hS7bFZSJCCZvQHHDMyRA==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:QCuU5c+36nw=,iv:zZTN4HfrUvD2V3cYKHI0kGunfiJ7wpS3Tr6g5phIUs0=,tag:Ky1+C/ElMXqYeyzNWNZoJg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:goSghPY/Jp2GWKyMyl1D9unkkTVYapOE8Q+c9detljyiy/54bFoqCNAG8aep/mmwIbm2/OyZj0AxMBJE,iv:krSOCE4BTAPCsr35YxwUiGXjsKhxYivPS+3q1jvT7gs=,tag:EHfYK9dzQicLkOlLlVIl+g==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:OqbGgUKAd6tCQhNmR15DliDaR9tQoywe4bULTtRi49SGNrXpvDqQrwdPLqiXCUo0SYd61TgJsvlr3Y0v9P4c8g7oCR3qjjc+Dy0/0ubKGhPO1+7qmC1RoNxIdbiJmYX6NPsEx64wXxFt6S6obRn5KWmpMadvjyzAke5bUYmig68=,iv:yDD7ITy2t7/I0PwSqBQvzgCjrTj25jhNhFSEDkJZ4yQ=,tag:qEhUkSLoNC+vuEaDr5cNrg==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:gCcduzUr19e9Fc9D0OVr5w==,iv:g3qaclKgKmvL3EoNpoHSUb3wYcc+IAPhoP6OK2CT7zY=,tag:eubvLtWG0rZkaTo6bVTAmw==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:EAtjpg==,iv:nYWqVYlfysj7HwPQBiQ/tLFXAcdtgLhAK9hopP7EPOE=,tag:72hlIXk1DWshMs+TFe6ffg==,type:str]
    TRTC_PASSWORD: ENC[AES256_GCM,data:hDQGzP1z/rnpk1PNsS7OPw==,iv:BUhlOzdPoXvRsC5QxmtqXol5W88whR4SaX1B8B/L/H4=,tag:RUyvOmPgMJ1OGSSf0p5jXw==,type:str]
    TRTC_USERNAME: ENC[AES256_GCM,data:aRRAxoGGR8GvuXYz9wBi2dF6cT35XPWK/UE4Mp2W0L8=,iv:TPRn+ByzPOfKX23Fs1T+F1UHYQhhqzXX28e9H3SCvtk=,tag:UInJmGa6EaUxVgmdq80YtA==,type:str]
kind: Secret
metadata:
    name: rider-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1U2hnV0pDTmczd3R4ME1Q
            YlFOTDdSWEZQMTNCVk8rN2pMd3R5ZlhVRlY0CnZqRWh4WTMrSUg2OWhFQjdpWDd0
            UXVUb1RXMXhzUVR1Z3pYbDQrMHlkWU0KLS0tIGtSUmNRWTltbXR3SEg0N25UWWRr
            bTFDcHlWVnZqU1BaK21nRk0vemZDY00KRYXWBZctEoLGh7xZuDtg97EL22uvqGBT
            ot0JHdYhPVGi8U+NxOshruP5qM/dG9eDCp8uE/DQMzHFAn4Q16tcAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T05:35:07Z"
    mac: ENC[AES256_GCM,data:V16wt1SW9Fe6p8sSrtqggdPFZ04H411wqF6RC26htxxjKw/harVORAKD/RcFXs3UN49ReFMzxU/hNg1SJ8yS4CgxiTKoL7SVrrx/p+fl5w6NZO6m2k4Q041ijzuaIyq9YDqEEjqrPPZyVdCOu4qXr35eN4FlHwoLLcdV8VEtgbg=,iv:CBY7bayWtNBjlDi4UnHf4ZWayUAqt53thK/lWwg/gro=,tag:kVHcWes5iOijc3yX90gGRg==,type:str]
    version: 3.13.3
