apiVersion: v1
data:
    APP_ENV: ENC[AES256_GCM,data:zhODWVS3bIzMhLhYi2606A==,iv:UvlnQdbMeYbhQ9vrPQ72W8fij8gfTHFh3t8326cE5Gc=,tag:/j1PKlU/X3l6cjxhek1UEQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:PGLDTb7iGfkX+TmjP7Kqt99Nbyax7uMZ7wqmN/06+LKoiNWM8iGkKFuHQtmgAvV2W+zL9LsL6/CjdG5gztcg1VxVhIqKIwe2Rbqmiou4+12aR6zkz1bItE4fw+IgFYTRJC0OteOPSU9Uru6RTNXEN1UV7FI1pHYd,iv:nEAJwg/qZvHMRHSsxQ9v4AQe8FTacMFxUYZYc8JB3XE=,tag:ztIsB/xKAunGMyCJrUAHig==,type:str]
    FIREBASE_ENABLED: ENC[AES256_GCM,data:JMmGI7FP2m0=,iv:jEdMoE9RjCJ48f77PAwjye9U0dYhjoMzZhiDpfW0Pqc=,tag:SFGa9jY9jCRBRlSVeFwooQ==,type:str]
    FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:q7jkgxPjgnL7Xs+qD9u4Cg==,iv:lO3zmLwLdARVfDROWc1TDyrq7g6dKbWIKb8wf5jtHx0=,tag:0BwM/ymeGqQSfiKU3DCdBQ==,type:str]
    GOOGLE_APPLICATION_CREDENTIALS: ENC[AES256_GCM,data:IjHp0HLBwrb0tpdACABYwmGYO/kUV0kqRyIT3w+gTsPgYEsDgCUDzQ==,iv:UYxKJ5HS9BMBpDK97C8zWOUwm65fuI2afH4+9C0zpS4=,tag:/CahRdRbla92LoKhq+386A==,type:str]
    PG_SCHEMA: ENC[AES256_GCM,data:NGlFqxAsEn0=,iv:IqGwI6pbJTiRwVUpvUpL1llPdmvB0ZtzjN45UPA0mW8=,tag:K2hAITTzolaUcwO7a+Z2Rg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:vFWHA1GDcXkvQM33Jpi6DUhUjj8sAIHYYTtO/nNFXHHCI4CEoIRWkYvMq7u5D6d1OjgJFcgIOzkMKCm8,iv:bLgSqzMz13KjXqHcITltEWpds8hQ3JK3nt2Uq0FcEKQ=,tag:BA5P4PccVRuVRLbLuINe0Q==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:H9BReiYhwfATNxo7oz/MYtL33GBE0hO+GvipT2dHh0n2Tn+aRuqQYz0RvZOfUQi4uwoQflgLKEThYwsPS9MNDxbhVcicAziVbl1rObGFl1FuGIEKPO3q5AQ6wR1Aqtnyyt71OPiZitCuO0Hv5Rn1NE6DrNbznyBR+LblmsndgpM=,iv:OKjVOrMq8P3MeDp+d18c637wAQsynCnkVOB/4Q4fV1s=,tag:UkPrWaob3SMBey9fkJpBTA==,type:str]
    SENTRY_ENVIRONMENT: ENC[AES256_GCM,data:yDkqFqOJKZElIvy2FvEP/Q==,iv:VqURAOAy2f1Y7YffAbT/cdi+NnJc9E1twAVcdN0thIU=,tag:rrM6JulLnjhxbbBKCANt8A==,type:str]
    SENTRY_TRACES_SAMPLE_RATE: ENC[AES256_GCM,data:IK8v9g==,iv:excrnorsObwfiW5LY1g5jA52NMspJfokyVxOmJaX7sI=,tag:XduEnSfpQJG3+JK/N46gkA==,type:str]
    TRTC_PASSWORD: ENC[AES256_GCM,data:fSRbDUrkvQzwNV8q3eRfZA==,iv:jRks6agWJ9Hjgnpz62AqpOIRrLbFwCixKrUCtUh8DCk=,tag:0pZnekzjshtQnhMlfhi9Wg==,type:str]
    TRTC_USERNAME: ENC[AES256_GCM,data:hBounk+04nkWqG/BAtmhxt0/Dwycbb51KrQze1PK6t4=,iv:slg2gWkPZGyRkwrKGSOMMxwSKSH8nYVcoQCm4NwJIZY=,tag:u0u/SFQLseshhyAO5v01cA==,type:str]
kind: Secret
metadata:
    name: rider-env
    namespace: bus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUG1VdXFKUE02U1YzT0dz
            aENwQ3d0NmtUbm5NZ0M1Mit6NTRCRVVGakVzClBjV2N0SWxsVkE4Vjc0MEZvd2k2
            UDVTVThWWHJ6ajVnL0hQU2I0STBZSjQKLS0tIC96a1VwaW0zYWZDS1piczNicGxN
            eUxFV0F0cGdRcDB3UGNUZlNjdUJMSEUK0C5MUtiSbqFpK7daiqobwANHh4cMTUJa
            wIbxK1qPRtJwgJ8eq48TJ3vlp3ySTzIA4hBn2JIT1WXVeYBFhH+yYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age126dq405qx03e5f67qqrrfkrh7gqasklrn44ym055t5f33m4emqws4fzfrf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T04:25:42Z"
    mac: ENC[AES256_GCM,data:2bjkzBLWsw/py8OfsGeHKASeKJjIgAGXvx8CdI7JA4KhLSXwlVxgsqZkL04YtT7jChqXo7iD2y7oBlDcMNPjbGN3qj/Rr0Tac+GHx3L8eotc+uMqfN0sGBFGt9i3YJKzgO/oMXttoaUd7LMzv6Lg9WCiUXYmiaEb3o0AnglDyLs=,iv:UboxJGqZjItbRcBsb7tr3urBXjODG6CcFBzq35VX8NA=,tag:oZ2kfYHSa/0wDIuql8Qg3A==,type:str]
    version: 3.13.3
